<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_dTk88JEuEeqRyKCsP6SKxA" name="DecisionMaking" author="alexpavtoulov" bonitaVersion="7.10.0" bonitaModelVersion="7.10.0-001" configId="ACED0005740010372E31302E302D303031372E31302E30">
    <elements xmi:type="process:Pool" xmi:id="_dTk88ZEuEeqRyKCsP6SKxA" name="Classification">
      <elements xmi:type="process:Lane" xmi:id="_dTk88pEuEeqRyKCsP6SKxA" name="Classify decisions" actor="_dTk9C5EuEeqRyKCsP6SKxA">
        <elements xmi:type="process:StartMessageEvent" xmi:id="_e_EY8JEvEeqRyKCsP6SKxA" name="Decision to arrive at" outgoing="_dTk9CJEuEeqRyKCsP6SKxA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dTk89JEuEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dTk89ZEuEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dTk89pEuEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <messageContent xmi:type="expression:Operation" xmi:id="_jYKgIJEvEeqRyKCsP6SKxA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_jYNjcZEvEeqRyKCsP6SKxA" content=""/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_jYNjcJEvEeqRyKCsP6SKxA" content=""/>
            <operator xmi:type="expression:Operator" xmi:id="_jYKgIZEvEeqRyKCsP6SKxA" type="ASSIGNMENT"/>
          </messageContent>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_P356oJExEeqRyKCsP6SKxA" documentation="by similarity" name="Lookup past decisions" outgoing="_SSUSIJEyEeqRyKCsP6SKxA" incoming="_dTk9CJEuEeqRyKCsP6SKxA _S75IYJxbEeqp0LuU99oBBQ">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_SSZfwJE0EeqRyKCsP6SKxA" source="_SSXDgJE0EeqRyKCsP6SKxA"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dTk8-JEuEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dTk8-ZEuEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dTk8-pEuEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dTk8-5EuEeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dTk8_JEuEeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dTk8_ZEuEeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dTk8_pEuEeqRyKCsP6SKxA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dTk8_5EuEeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_sJp5AJExEeqRyKCsP6SKxA" name="Classify" outgoing="_y5nw8JExEeqRyKCsP6SKxA _zqd_EJExEeqRyKCsP6SKxA _0ipkQJExEeqRyKCsP6SKxA" incoming="_qtQMcJExEeqRyKCsP6SKxA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qtIQopExEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qtIQoZExEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qtIQo5ExEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_y5dY4JExEeqRyKCsP6SKxA" name="Autonomous decision making" incoming="_y5nw8JExEeqRyKCsP6SKxA" outgoingMessages="_NDGk0JE-EeqRyKCsP6SKxA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_y5dY4pExEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_y5dY4ZExEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_y5dY45ExEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_NDCTYJE-EeqRyKCsP6SKxA" name="Autonomous Decision">
            <correlation xmi:type="process:Correlation" xmi:id="_NDCTYZE-EeqRyKCsP6SKxA">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_NDCTYpE-EeqRyKCsP6SKxA"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_NDCTY5E-EeqRyKCsP6SKxA" name="Simulation" content="Simulation" returnTypeFixed="true"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_NDCTZJE-EeqRyKCsP6SKxA" name="Decision to arrive at" content="Decision to arrive at" returnTypeFixed="true"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_NDCTZZE-EeqRyKCsP6SKxA">
              <expressions xmi:type="expression:ListExpression" xmi:id="_NDCTZpE-EeqRyKCsP6SKxA">
                <expressions xmi:type="expression:Expression" xmi:id="_NDCTZ5E-EeqRyKCsP6SKxA" name="decision" content="decision" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_NDCTaJE-EeqRyKCsP6SKxA" name="5" content="5"/>
              </expressions>
            </messageContent>
          </events>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_zqX4cJExEeqRyKCsP6SKxA" name="Human assisted decision-making" incoming="_zqd_EJExEeqRyKCsP6SKxA" outgoingMessages="_6RTgcJFCEeqYebkRM8FsyA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zqX4cpExEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zqX4cZExEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zqX4c5ExEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_6RQdIJFCEeqYebkRM8FsyA" name="HumanAssistedDecisionMessage">
            <correlation xmi:type="process:Correlation" xmi:id="_6RQdIZFCEeqYebkRM8FsyA">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_6RQdIpFCEeqYebkRM8FsyA"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_6RQdI5FCEeqYebkRM8FsyA" name="Simulation" content="Simulation" returnTypeFixed="true"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_6RQdJJFCEeqYebkRM8FsyA" name="Decision to arrive at" content="Decision to arrive at" returnTypeFixed="true"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_6RQdJZFCEeqYebkRM8FsyA">
              <expressions xmi:type="expression:ListExpression" xmi:id="_6RQdJpFCEeqYebkRM8FsyA">
                <expressions xmi:type="expression:Expression" xmi:id="_6RQdJ5FCEeqYebkRM8FsyA" content="" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_6RQdKJFCEeqYebkRM8FsyA"/>
              </expressions>
            </messageContent>
          </events>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_0ijdoJExEeqRyKCsP6SKxA" name="Human decision-making" incoming="_0ipkQJExEeqRyKCsP6SKxA" outgoingMessages="_AqkIkJFDEeqYebkRM8FsyA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0ijdopExEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0ijdoZExEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0ijdo5ExEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_AqjhgJFDEeqYebkRM8FsyA" name="HumanDecisionMessage">
            <correlation xmi:type="process:Correlation" xmi:id="_AqjhgZFDEeqYebkRM8FsyA">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_AqjhgpFDEeqYebkRM8FsyA"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_Aqjhg5FDEeqYebkRM8FsyA" name="Simulation" content="Simulation" returnTypeFixed="true"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_AqjhhJFDEeqYebkRM8FsyA" name="Decision to arrive at" content="Decision to arrive at" returnTypeFixed="true"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_AqjhhZFDEeqYebkRM8FsyA">
              <expressions xmi:type="expression:ListExpression" xmi:id="_AqjhhpFDEeqYebkRM8FsyA">
                <expressions xmi:type="expression:Expression" xmi:id="_Aqjhh5FDEeqYebkRM8FsyA" content="" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_AqjhiJFDEeqYebkRM8FsyA"/>
              </expressions>
            </messageContent>
          </events>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_SSQnwJEyEeqRyKCsP6SKxA" name="Lookup filter criteria" outgoing="_dBS9UJEyEeqRyKCsP6SKxA" incoming="_SSUSIJEyEeqRyKCsP6SKxA">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_xtBwEJEzEeqRyKCsP6SKxA" source="_xs_T0JEzEeqRyKCsP6SKxA"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SSQnwpEyEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SSQnwZEyEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SSQnw5EyEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SSQnxJEyEeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SSQnxZEyEeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SSQnxpEyEeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SSQnyJEyEeqRyKCsP6SKxA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SSQnx5EyEeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_f1ZcoJEyEeqRyKCsP6SKxA" name="Classification score" outgoing="_qtQMcJExEeqRyKCsP6SKxA" incoming="_dBS9UJEyEeqRyKCsP6SKxA">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_kTcVQJEyEeqRyKCsP6SKxA" source="_kTUZcJEyEeqRyKCsP6SKxA"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dBQhEpEyEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dBQhEZEyEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dBQhE5EyEeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dBQhFJEyEeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dBQhFZEyEeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dBQhFpEyEeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dBQhGJEyEeqRyKCsP6SKxA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dBQhF5EyEeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_kTUZcJEyEeqRyKCsP6SKxA" text="Evaluate a score for every classification option based on past decisions' quality and pre-defined filters"/>
        <elements xmi:type="process:TextAnnotation" xmi:id="_xs_T0JEzEeqRyKCsP6SKxA" text="Filters that are defined by system admins. Appropriate for:&#xA;- Decisions that the AI is not yet capable to perform and\or &#xA;- Have critical concequences for the entire system&#xA;- Decisions that require personal preference inputs&#xA;- More?"/>
        <elements xmi:type="process:TextAnnotation" xmi:id="_SSXDgJE0EeqRyKCsP6SKxA" text="The quality score of previous similar decisions that is taken into consideration in the classification"/>
        <elements xmi:type="process:IntermediateCatchMessageEvent" xmi:id="_R3-0UJxbEeqp0LuU99oBBQ" name="Catch simulated decision" outgoing="_S75IYJxbEeqp0LuU99oBBQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_R3_bYZxbEeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_R3_bYJxbEeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_R3_bYpxbEeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_lp0ncJE0EeqRyKCsP6SKxA" name="Assess decision quality score">
        <elements xmi:type="process:StartTimerEvent" xmi:id="_7gVAsJE0EeqRyKCsP6SKxA" name="Periodic evaluation" outgoing="_Eb0VAJE1EeqRyKCsP6SKxA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7gVAspE0EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7gVAsZE0EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7gVAs5E0EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_8bDjkJE0EeqRyKCsP6SKxA" name="0 0 12 ? * MON *" content="0 0 12 ? * MON *"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_hs8FsJE1EeqRyKCsP6SKxA" name="Collect human feedback" outgoing="_kMVjgJE5EeqRyKCsP6SKxA" incoming="_O9s_YJE1EeqRyKCsP6SKxA" type="PARALLEL" storeOutput="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_O9qjIZE1EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_O9qjIJE1EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_O9qjIpE1EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_O9qjI5E1EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_O9qjJJE1EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_O9qjJZE1EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_O9qjJ5E1EeqRyKCsP6SKxA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_O9qjJpE1EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_hs8FupE1EeqRyKCsP6SKxA">
            <targetForm xmi:type="expression:Expression" xmi:id="_hs8Fu5E1EeqRyKCsP6SKxA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_hs8FuZE1EeqRyKCsP6SKxA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_hs8FvJE1EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_tGuocJE1EeqRyKCsP6SKxA" name="Collect autonomous feedback" outgoing="_l0cJwJE5EeqRyKCsP6SKxA" incoming="_tGxEsJE1EeqRyKCsP6SKxA" type="PARALLEL">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tGuocpE1EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tGuocZE1EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tGuoc5E1EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_tGuodJE1EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_tGuodZE1EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tGuodpE1EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_tGuoeJE1EeqRyKCsP6SKxA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_tGuod5E1EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_kMTHQJE5EeqRyKCsP6SKxA" name="Unite" outgoing="_v3aDgJE5EeqRyKCsP6SKxA" incoming="_kMVjgJE5EeqRyKCsP6SKxA _l0cJwJE5EeqRyKCsP6SKxA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kMTuUZE5EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kMTuUJE5EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kMTuUpE5EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_lIzLwJE5EeqRyKCsP6SKxA" name="Parallelize" outgoing="_O9s_YJE1EeqRyKCsP6SKxA _tGxEsJE1EeqRyKCsP6SKxA" incoming="_QvLkEJE1EeqRyKCsP6SKxA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QvJH0pE1EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QvJH0ZE1EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QvJH05E1EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_G1OqIJE6EeqRyKCsP6SKxA" name="Store quality score" outgoing="_oPjZ8JE8EeqRyKCsP6SKxA" incoming="_G1RGYJE6EeqRyKCsP6SKxA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_G1OqIpE6EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_G1OqIZE6EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_G1OqI5E6EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_G1OqJJE6EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_G1OqJZE6EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_G1OqJpE6EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_G1OqKJE6EeqRyKCsP6SKxA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_G1OqJ5E6EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_L5DwYJE6EeqRyKCsP6SKxA" name="Assess quality score" outgoing="_G1RGYJE6EeqRyKCsP6SKxA" incoming="_v3aDgJE5EeqRyKCsP6SKxA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_v3XnQpE5EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_v3XnQZE5EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_v3XnQ5E5EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_v3XnRJE5EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_v3XnRZE5EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_v3XnRpE5EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_v3XnSJE5EeqRyKCsP6SKxA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_v3XnR5E5EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_oPfIgJE8EeqRyKCsP6SKxA" name="End1" incoming="_oPjZ8JE8EeqRyKCsP6SKxA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oPg9sZE8EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oPg9sJE8EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oPg9spE8EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_1ExY4JE8EeqRyKCsP6SKxA" text="- Residents&#xA;- Visitors&#xA;- Admins&#xA;- Systems&#xA;..."/>
        <elements xmi:type="process:ServiceTask" xmi:id="_y1540JxZEeqp0LuU99oBBQ" name="Locate stakeholders" outgoing="_QvLkEJE1EeqRyKCsP6SKxA" incoming="_Eb0VAJE1EeqRyKCsP6SKxA _G-ZmgJE1EeqRyKCsP6SKxA">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_1EzOEJE8EeqRyKCsP6SKxA" source="_1ExY4JE8EeqRyKCsP6SKxA"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ebx4wZE1EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Ebx4wJE1EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Ebx4wpE1EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Ebx4w5E1EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Ebx4xJE1EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Ebx4xZE1EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Ebx4x5E1EeqRyKCsP6SKxA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Ebx4xpE1EeqRyKCsP6SKxA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartMessageEvent" xmi:id="_PC7vQJxaEeqp0LuU99oBBQ" name="Evaluation request" outgoing="_G-ZmgJE1EeqRyKCsP6SKxA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GVnvQpE1EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GVnvQZE1EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GVnvQ5E1EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_dTk9BJEuEeqRyKCsP6SKxA">
        <targetForm xmi:type="expression:Expression" xmi:id="_dTk9BZEuEeqRyKCsP6SKxA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_dTk9BpEuEeqRyKCsP6SKxA">
        <targetForm xmi:type="expression:Expression" xmi:id="_dTk9B5EuEeqRyKCsP6SKxA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dTk9CJEuEeqRyKCsP6SKxA" target="_P356oJExEeqRyKCsP6SKxA" source="_e_EY8JEvEeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dTk9CZEuEeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_dTk9CpEuEeqRyKCsP6SKxA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qtQMcJExEeqRyKCsP6SKxA" target="_sJp5AJExEeqRyKCsP6SKxA" source="_f1ZcoJEyEeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qtQzgJExEeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_qtQzgZExEeqRyKCsP6SKxA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_y5nw8JExEeqRyKCsP6SKxA" target="_y5dY4JExEeqRyKCsP6SKxA" source="_sJp5AJExEeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_y5nw8ZExEeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_y5nw8pExEeqRyKCsP6SKxA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zqd_EJExEeqRyKCsP6SKxA" target="_zqX4cJExEeqRyKCsP6SKxA" source="_sJp5AJExEeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zqd_EZExEeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_zqd_EpExEeqRyKCsP6SKxA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0ipkQJExEeqRyKCsP6SKxA" target="_0ijdoJExEeqRyKCsP6SKxA" source="_sJp5AJExEeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0ipkQZExEeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_0ipkQpExEeqRyKCsP6SKxA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SSUSIJEyEeqRyKCsP6SKxA" target="_SSQnwJEyEeqRyKCsP6SKxA" source="_P356oJExEeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SSUSIZEyEeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_SSUSIpEyEeqRyKCsP6SKxA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dBS9UJEyEeqRyKCsP6SKxA" target="_f1ZcoJEyEeqRyKCsP6SKxA" source="_SSQnwJEyEeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dBTkYJEyEeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_dBTkYZEyEeqRyKCsP6SKxA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Eb0VAJE1EeqRyKCsP6SKxA" target="_y1540JxZEeqp0LuU99oBBQ" source="_7gVAsJE0EeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Eb0VAZE1EeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Eb0VApE1EeqRyKCsP6SKxA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_G-ZmgJE1EeqRyKCsP6SKxA" target="_y1540JxZEeqp0LuU99oBBQ" source="_PC7vQJxaEeqp0LuU99oBBQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_G-ZmgZE1EeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_G-ZmgpE1EeqRyKCsP6SKxA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_O9s_YJE1EeqRyKCsP6SKxA" target="_hs8FsJE1EeqRyKCsP6SKxA" source="_lIzLwJE5EeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_O9s_YZE1EeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_lI1oAJE5EeqRyKCsP6SKxA" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QvLkEJE1EeqRyKCsP6SKxA" target="_lIzLwJE5EeqRyKCsP6SKxA" source="_y1540JxZEeqp0LuU99oBBQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QvMLIJE1EeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_lI2PEZE5EeqRyKCsP6SKxA" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tGxEsJE1EeqRyKCsP6SKxA" target="_tGuocJE1EeqRyKCsP6SKxA" source="_lIzLwJE5EeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tGxEsZE1EeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_lI2PEJE5EeqRyKCsP6SKxA" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kMVjgJE5EeqRyKCsP6SKxA" target="_kMTHQJE5EeqRyKCsP6SKxA" source="_hs8FsJE1EeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kMVjgZE5EeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_kMWKkJE5EeqRyKCsP6SKxA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_l0cJwJE5EeqRyKCsP6SKxA" target="_kMTHQJE5EeqRyKCsP6SKxA" source="_tGuocJE1EeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_l0cw0JE5EeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_l0cw0ZE5EeqRyKCsP6SKxA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_v3aDgJE5EeqRyKCsP6SKxA" target="_L5DwYJE6EeqRyKCsP6SKxA" source="_kMTHQJE5EeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_v3aDgZE5EeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_v3aDgpE5EeqRyKCsP6SKxA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_G1RGYJE6EeqRyKCsP6SKxA" target="_G1OqIJE6EeqRyKCsP6SKxA" source="_L5DwYJE6EeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_G1RGYZE6EeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_G1RGYpE6EeqRyKCsP6SKxA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oPjZ8JE8EeqRyKCsP6SKxA" target="_oPfIgJE8EeqRyKCsP6SKxA" source="_G1OqIJE6EeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oPkBAJE8EeqRyKCsP6SKxA"/>
        <condition xmi:type="expression:Expression" xmi:id="_oPkBAZE8EeqRyKCsP6SKxA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_S75IYJxbEeqp0LuU99oBBQ" target="_P356oJExEeqRyKCsP6SKxA" source="_R3-0UJxbEeqp0LuU99oBBQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_S75vcJxbEeqp0LuU99oBBQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_S75vcZxbEeqp0LuU99oBBQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_dTk9C5EuEeqRyKCsP6SKxA" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_dTk9DJEuEeqRyKCsP6SKxA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dTk9DZEuEeqRyKCsP6SKxA">
        <name xmi:type="expression:Expression" xmi:id="_dTk9DpEuEeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dTk9D5EuEeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dTk9EJEuEeqRyKCsP6SKxA">
        <name xmi:type="expression:Expression" xmi:id="_dTk9EZEuEeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dTk9EpEuEeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dTk9E5EuEeqRyKCsP6SKxA">
        <name xmi:type="expression:Expression" xmi:id="_dTk9FJEuEeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dTk9FZEuEeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dTk9FpEuEeqRyKCsP6SKxA">
        <name xmi:type="expression:Expression" xmi:id="_dTk9F5EuEeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dTk9GJEuEeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dTk9GZEuEeqRyKCsP6SKxA">
        <name xmi:type="expression:Expression" xmi:id="_dTk9GpEuEeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dTk9G5EuEeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_WMgOwJE9EeqRyKCsP6SKxA" name="Decision Making">
      <elements xmi:type="process:Lane" xmi:id="_ctKfYJE9EeqRyKCsP6SKxA" name="Autonomous decision-making">
        <elements xmi:type="process:StartMessageEvent" xmi:id="_6ZlE8JE9EeqRyKCsP6SKxA" name="Decision to arrive at" outgoing="_zUT5IJFCEeqYebkRM8FsyA" event="Autonomous Decision" incomingMessag="_NDGk0JE-EeqRyKCsP6SKxA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6ZlE8pE9EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6ZlE8ZE9EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6ZlE85E9EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_5wtVUJw5Eeqp0LuU99oBBQ" name="Generate alternatives" outgoing="_6WOdMJw5Eeqp0LuU99oBBQ" incoming="_zUT5IJFCEeqYebkRM8FsyA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zT8FsZFCEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zT8FsJFCEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zT8FspFCEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_zT8Fs5FCEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_zT8FtJFCEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_zT8swJFCEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_zT8swpFCEeqYebkRM8FsyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_zT8swZFCEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_7Lq3cJw5Eeqp0LuU99oBBQ" name="Arrive at a decision" outgoing="_DNqX8Jw6Eeqp0LuU99oBBQ" incoming="_6ucv8Jw5Eeqp0LuU99oBBQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6uZsoZw5Eeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6uZsoJw5Eeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6uZsopw5Eeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6uZso5w5Eeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6uZspJw5Eeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_6uZspZw5Eeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_6uZsp5w5Eeqp0LuU99oBBQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_6uZsppw5Eeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_73SnUJw5Eeqp0LuU99oBBQ" name="Evaluate a score for each alternative" outgoing="_6ucv8Jw5Eeqp0LuU99oBBQ" incoming="_6WOdMJw5Eeqp0LuU99oBBQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6WEsMZw5Eeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6WEsMJw5Eeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6WEsMpw5Eeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6WEsM5w5Eeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6WEsNJw5Eeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_6WEsNZw5Eeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_6WFTQJw5Eeqp0LuU99oBBQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_6WEsNpw5Eeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_DNhOAJw6Eeqp0LuU99oBBQ" name="Publish decision" incoming="_DNqX8Jw6Eeqp0LuU99oBBQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DNh1EZw6Eeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DNh1EJw6Eeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DNh1Epw6Eeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_gHn0EJE9EeqRyKCsP6SKxA" name="Human assisted decision-making">
        <elements xmi:type="process:StartMessageEvent" xmi:id="_66v4UJE9EeqRyKCsP6SKxA" name="Decision to arrive at" outgoing="_G-tnMJFDEeqYebkRM8FsyA" event="HumanAssistedDecisionMessage" incomingMessag="_6RTgcJFCEeqYebkRM8FsyA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_66wfYZE9EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_66wfYJE9EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_66wfYpE9EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_pmNmsJFDEeqYebkRM8FsyA" name="Generate alternatives" outgoing="_MHWU8JFDEeqYebkRM8FsyA" incoming="_G-tnMJFDEeqYebkRM8FsyA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_G-p80ZFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_G-p80JFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_G-p80pFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_G-p805FDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_G-p81JFDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_G-p81ZFDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_G-p815FDEeqYebkRM8FsyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_G-p81pFDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_qsZLoJFDEeqYebkRM8FsyA" name="Evaluate a score for each alternative" outgoing="_Gk-SAJw6Eeqp0LuU99oBBQ" incoming="_MHWU8JFDEeqYebkRM8FsyA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MHSqkZFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MHSqkJFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MHSqkpFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_MHSqk5FDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_MHSqlJFDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_MHSqlZFDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_MHSql5FDEeqYebkRM8FsyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_MHSqlpFDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_zU2PMJFDEeqYebkRM8FsyA" name="Arrive at a decision" outgoing="_3ebTsJFDEeqYebkRM8FsyA" incoming="_w1ge8JFDEeqYebkRM8FsyA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_w1c0kZFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_w1c0kJFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_w1c0kpFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_w1c0k5FDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_w1c0lJFDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_w1c0lZFDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_w1c0l5FDEeqYebkRM8FsyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_w1c0lpFDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_3eV0IJFDEeqYebkRM8FsyA" name="Publish Decision" incoming="_3ebTsJFDEeqYebkRM8FsyA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3eV0IpFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3eV0IZFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3eV0I5FDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_K0F90Jw6Eeqp0LuU99oBBQ" name="Get human feedback and corrections" outgoing="_w1ge8JFDEeqYebkRM8FsyA" incoming="_Gk-SAJw6Eeqp0LuU99oBBQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Gk6AkZw6Eeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Gk6AkJw6Eeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Gk6Akpw6Eeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Gk6Ak5w6Eeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Gk6AlJw6Eeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Gk6AlZw6Eeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Gk6Al5w6Eeqp0LuU99oBBQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Gk6Alpw6Eeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_K0HL9Jw6Eeqp0LuU99oBBQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_K0HL9Zw6Eeqp0LuU99oBBQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_K0HL85w6Eeqp0LuU99oBBQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_K0HL9pw6Eeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_gZXrYJE9EeqRyKCsP6SKxA" name="Human decision-making">
        <elements xmi:type="process:StartMessageEvent" xmi:id="_7mVzAJE9EeqRyKCsP6SKxA" name="Decision to arrive at" outgoing="_1Hum8LJREeq_W6pXnlyepA" event="HumanDecisionMessage" incomingMessag="_AqkIkJFDEeqYebkRM8FsyA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7mWaEZE9EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7mWaEJE9EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7mWaEpE9EeqRyKCsP6SKxA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_HR07AJFEEeqYebkRM8FsyA" name="Notify and Publish result" outgoing="_J1zToJFEEeqYebkRM8FsyA" incoming="_Gk91AJFEEeqYebkRM8FsyA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Gk7YwZFEEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Gk7YwJFEEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Gk7YwpFEEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Gk7Yw5FEEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Gk7YxJFEEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Gk7YxZFEEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Gk7Yx5FEEeqYebkRM8FsyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Gk7YxpFEEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_J1t0EJFEEeqYebkRM8FsyA" name="End" incoming="_J1zToJFEEeqYebkRM8FsyA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_J1ubIJFEEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_J1t0EZFEEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_J1ubIZFEEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_-i0JsLJDEeq_W6pXnlyepA" name="Submit a proposal" outgoing="_iqo3gL08EeqGG6w3Dt49BQ" incoming="_d8vlAL08EeqGG6w3Dt49BQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4g8t4rJDEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4g8t4bJDEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4g8t47JDEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4g8t5LJDEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4g8t5bJDEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4g9U8LJDEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4g9U8rJDEeq_W6pXnlyepA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4g9U8bJDEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_DRCzYLJEEeq_W6pXnlyepA" name="Prioritization voting from stakeholders" outgoing="_oaadQLJFEeq_W6pXnlyepA" incoming="_iqo3gL08EeqGG6w3Dt49BQ _CAankL09EeqGG6w3Dt49BQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DRDacbJEEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DRDacLJEEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DRDacrJEEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_DRDac7JEEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_DRDadLJEEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_DRDadbJEEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_DRDad7JEEeq_W6pXnlyepA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_DRDadrJEEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_jpVwYLJEEeq_W6pXnlyepA" name="Pick decision makers" outgoing="_TRCucLJTEeq_W6pXnlyepA" incoming="_BcNuUL09EeqGG6w3Dt49BQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jpWXcbJEEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jpWXcLJEEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jpWXcrJEEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jpWXc7JEEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jpWXdLJEEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jpWXdbJEEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jpWXd7JEEeq_W6pXnlyepA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jpWXdrJEEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_xfH0cLJEEeq_W6pXnlyepA" name="Decide on voting type (Binary/Multiple/Dot voting)" outgoing="_SmpSoL1AEeqGG6w3Dt49BQ" incoming="_c17t8L08EeqGG6w3Dt49BQ">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_Dkuk4L07EeqGG6w3Dt49BQ" source="_DkpsYL07EeqGG6w3Dt49BQ"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xfIbgbJEEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xfIbgLJEEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xfIbgrJEEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xfIbg7JEEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xfIbhLJEEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xfIbhbJEEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xfIbh7JEEeq_W6pXnlyepA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xfIbhrJEEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_8_Hs4LJEEeq_W6pXnlyepA" name="Timer2" outgoing="_-qrPwLJEEeq_W6pXnlyepA" incoming="_8_TTELJEEeq_W6pXnlyepA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8_Hs4rJEEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8_Hs4bJEEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8_Hs47JEEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_NRxcALJFEeq_W6pXnlyepA" name="Pull voting result" outgoing="_Gk91AJFEEeqYebkRM8FsyA" incoming="_-qrPwLJEEeq_W6pXnlyepA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XQiP4ZFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XQiP4JFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XQiP4pFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XQiP45FDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XQiP5JFDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XQiP5ZFDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XQiP55FDEeqYebkRM8FsyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XQiP5pFDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_NuRx0LJFEeq_W6pXnlyepA" name="Initiate 'Decision makers' voting" outgoing="_8_TTELJEEeq_W6pXnlyepA" incoming="_UsYM4L08EeqGG6w3Dt49BQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dSF6cbJEEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dSF6cLJEEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dSF6crJEEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dSF6c7JEEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dSF6dLJEEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dSF6dbJEEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dSF6d7JEEeq_W6pXnlyepA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dSF6drJEEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_oaTvkLJFEeq_W6pXnlyepA" name="Timer1" outgoing="__YpUEL08EeqGG6w3Dt49BQ" incoming="_oaadQLJFEeq_W6pXnlyepA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oaTvkrJFEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oaTvkbJFEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oaTvk7JFEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_WSBlcLJOEeq_W6pXnlyepA" text="(which? ____) should ____ verb ___  noun ____ for/to ___(goal/motivation/purpose = why do &lt;verb>?)___&#xA;&#xA;* Should we build a farmbot to increase engagement of the center visitors?&#xA;* Which criteria should we use for new residents to maximize efficiency?&#xA;* Which platform should we use for effective decision making?&#xA;* Should we accept this new resident to complete the construction of the campus?&#xA;* should we implement a new project transparency dashboard on the TVP website to => retain existing supporters + improving conversion of the visitors&#xA;&#xA;Structured decision format:&#xA;* Options (&lt;- needs to be provided if 'which')&#xA;* Action (&lt;- verb+noun)&#xA;* Goal(s)"/>
        <elements xmi:type="process:ServiceTask" xmi:id="_1HrjoLJREeq_W6pXnlyepA" name="Inspect syntax and goal validity" outgoing="_7Q3IYLJREeq_W6pXnlyepA" incoming="_1Hum8LJREeq_W6pXnlyepA">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_WugtILJOEeq_W6pXnlyepA" source="_WSBlcLJOEeq_W6pXnlyepA"/>
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_Xk4dUL03EeqGG6w3Dt49BQ" source="_Uy-9cL03EeqGG6w3Dt49BQ"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1HsKsbJREeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1HsKsLJREeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1HsKsrJREeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_1HsKs7JREeq_W6pXnlyepA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_1HsKtLJREeq_W6pXnlyepA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_1HsKtbJREeq_W6pXnlyepA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_1HsKt7JREeq_W6pXnlyepA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_1HsKtrJREeq_W6pXnlyepA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_5p38cLJREeq_W6pXnlyepA" name="Reject" incoming="_5qAfULJREeq_W6pXnlyepA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5p4jgbJREeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5p4jgLJREeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5p4jgrJREeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_8ISfoLJREeq_W6pXnlyepA" name="XOR" outgoing="_5qAfULJREeq_W6pXnlyepA _c17t8L08EeqGG6w3Dt49BQ" incoming="_7Q3IYLJREeq_W6pXnlyepA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7Q1TMbJREeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7Q1TMLJREeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7Q1TMrJREeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_6vzX0LJTEeq_W6pXnlyepA" name="Accept/Reject/Delegate" outgoing="_pqfagLJEEeq_W6pXnlyepA" incoming="_TRCucLJTEeq_W6pXnlyepA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TRASMbJTEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TRASMLJTEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TRASMrJTEeq_W6pXnlyepA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_TRASM7JTEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_TRASNLJTEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_TRASNbJTEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_TRASN7JTEeq_W6pXnlyepA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_TRASNrJTEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_6vzX2rJTEeq_W6pXnlyepA">
            <targetForm xmi:type="expression:Expression" xmi:id="_6vzX27JTEeq_W6pXnlyepA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_6vzX2bJTEeq_W6pXnlyepA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_6vzX3LJTEeq_W6pXnlyepA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_Uy-9cL03EeqGG6w3Dt49BQ" text="Validate goal against database"/>
        <elements xmi:type="process:TextAnnotation" xmi:id="_DkpsYL07EeqGG6w3Dt49BQ" text="Which? -> Multiple choice (dot)&#xA;Should? -> Binary"/>
        <elements xmi:type="process:XORGateway" xmi:id="_AaWBoL09EeqGG6w3Dt49BQ" name="Threshold" outgoing="_BcNuUL09EeqGG6w3Dt49BQ _CAankL09EeqGG6w3Dt49BQ" incoming="__YpUEL08EeqGG6w3Dt49BQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__Yh_Ub08EeqGG6w3Dt49BQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__Yh_UL08EeqGG6w3Dt49BQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__Yh_Ur08EeqGG6w3Dt49BQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_mFY_wL0_EeqGG6w3Dt49BQ" name="Research for supporting data" outgoing="_UsYM4L08EeqGG6w3Dt49BQ" incoming="_pqfagLJEEeq_W6pXnlyepA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_9tVF8ZFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_9tVF8JFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_9tVF8pFDEeqYebkRM8FsyA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_9tVF85FDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_9tVF9JFDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_9tVF9ZFDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_9tVF95FDEeqYebkRM8FsyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_9tVF9pFDEeqYebkRM8FsyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_mFZm1r0_EeqGG6w3Dt49BQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_mFZm170_EeqGG6w3Dt49BQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_mFZm1b0_EeqGG6w3Dt49BQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_mFZm2L0_EeqGG6w3Dt49BQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_SmmPUL1AEeqGG6w3Dt49BQ" name="Pick stakeholders" outgoing="_d8vlAL08EeqGG6w3Dt49BQ" incoming="_SmpSoL1AEeqGG6w3Dt49BQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Smm2Yb1AEeqGG6w3Dt49BQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Smm2YL1AEeqGG6w3Dt49BQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Smm2Yr1AEeqGG6w3Dt49BQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Smm2Y71AEeqGG6w3Dt49BQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Smm2ZL1AEeqGG6w3Dt49BQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Smm2Zb1AEeqGG6w3Dt49BQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Smm2Z71AEeqGG6w3Dt49BQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Smm2Zr1AEeqGG6w3Dt49BQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_yM3I4JFCEeqYebkRM8FsyA" name="decision" dataType="_dTk9JJEuEeqRyKCsP6SKxA" className="org.RBE.decisions.Decision">
        <defaultValue xmi:type="expression:Expression" xmi:id="_yM3I4ZFCEeqYebkRM8FsyA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_WMg135E9EeqRyKCsP6SKxA">
        <targetForm xmi:type="expression:Expression" xmi:id="_WMg14JE9EeqRyKCsP6SKxA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_WMg14ZE9EeqRyKCsP6SKxA">
        <targetForm xmi:type="expression:Expression" xmi:id="_WMg14pE9EeqRyKCsP6SKxA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zUT5IJFCEeqYebkRM8FsyA" target="_5wtVUJw5Eeqp0LuU99oBBQ" source="_6ZlE8JE9EeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zUT5IZFCEeqYebkRM8FsyA"/>
        <condition xmi:type="expression:Expression" xmi:id="_zUUgMJFCEeqYebkRM8FsyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_G-tnMJFDEeqYebkRM8FsyA" target="_pmNmsJFDEeqYebkRM8FsyA" source="_66v4UJE9EeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_G-tnMZFDEeqYebkRM8FsyA"/>
        <condition xmi:type="expression:Expression" xmi:id="_G-tnMpFDEeqYebkRM8FsyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MHWU8JFDEeqYebkRM8FsyA" target="_qsZLoJFDEeqYebkRM8FsyA" source="_pmNmsJFDEeqYebkRM8FsyA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MHWU8ZFDEeqYebkRM8FsyA"/>
        <condition xmi:type="expression:Expression" xmi:id="_MHWU8pFDEeqYebkRM8FsyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_w1ge8JFDEeqYebkRM8FsyA" target="_zU2PMJFDEeqYebkRM8FsyA" source="_K0F90Jw6Eeqp0LuU99oBBQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_w1ge8ZFDEeqYebkRM8FsyA"/>
        <condition xmi:type="expression:Expression" xmi:id="_w1ge8pFDEeqYebkRM8FsyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3ebTsJFDEeqYebkRM8FsyA" target="_3eV0IJFDEeqYebkRM8FsyA" source="_zU2PMJFDEeqYebkRM8FsyA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3eb6wJFDEeqYebkRM8FsyA"/>
        <condition xmi:type="expression:Expression" xmi:id="_3eb6wZFDEeqYebkRM8FsyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Gk91AJFEEeqYebkRM8FsyA" target="_HR07AJFEEeqYebkRM8FsyA" source="_NRxcALJFEeq_W6pXnlyepA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Gk91AZFEEeqYebkRM8FsyA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Gk91ApFEEeqYebkRM8FsyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_J1zToJFEEeqYebkRM8FsyA" target="_J1t0EJFEEeqYebkRM8FsyA" source="_HR07AJFEEeqYebkRM8FsyA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_J1zToZFEEeqYebkRM8FsyA"/>
        <condition xmi:type="expression:Expression" xmi:id="_J1zTopFEEeqYebkRM8FsyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6WOdMJw5Eeqp0LuU99oBBQ" target="_73SnUJw5Eeqp0LuU99oBBQ" source="_5wtVUJw5Eeqp0LuU99oBBQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6WPEQJw5Eeqp0LuU99oBBQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_6WPEQZw5Eeqp0LuU99oBBQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6ucv8Jw5Eeqp0LuU99oBBQ" target="_7Lq3cJw5Eeqp0LuU99oBBQ" source="_73SnUJw5Eeqp0LuU99oBBQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6ucv8Zw5Eeqp0LuU99oBBQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_6ucv8pw5Eeqp0LuU99oBBQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DNqX8Jw6Eeqp0LuU99oBBQ" target="_DNhOAJw6Eeqp0LuU99oBBQ" source="_7Lq3cJw5Eeqp0LuU99oBBQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DNqX8Zw6Eeqp0LuU99oBBQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_DNq_AJw6Eeqp0LuU99oBBQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Gk-SAJw6Eeqp0LuU99oBBQ" target="_K0F90Jw6Eeqp0LuU99oBBQ" source="_qsZLoJFDEeqYebkRM8FsyA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Gk-SAZw6Eeqp0LuU99oBBQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Gk-SApw6Eeqp0LuU99oBBQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pqfagLJEEeq_W6pXnlyepA" target="_mFY_wL0_EeqGG6w3Dt49BQ" source="_6vzX0LJTEeq_W6pXnlyepA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pqgBkLJEEeq_W6pXnlyepA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pqgBkbJEEeq_W6pXnlyepA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8_TTELJEEeq_W6pXnlyepA" target="_8_Hs4LJEEeq_W6pXnlyepA" source="_NuRx0LJFEeq_W6pXnlyepA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8_TTEbJEEeq_W6pXnlyepA"/>
        <condition xmi:type="expression:Expression" xmi:id="_8_TTErJEEeq_W6pXnlyepA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-qrPwLJEEeq_W6pXnlyepA" target="_NRxcALJFEeq_W6pXnlyepA" source="_8_Hs4LJEEeq_W6pXnlyepA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-qrPwbJEEeq_W6pXnlyepA"/>
        <condition xmi:type="expression:Expression" xmi:id="_-qrPwrJEEeq_W6pXnlyepA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oaadQLJFEeq_W6pXnlyepA" target="_oaTvkLJFEeq_W6pXnlyepA" source="_DRCzYLJEEeq_W6pXnlyepA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oaadQbJFEeq_W6pXnlyepA"/>
        <condition xmi:type="expression:Expression" xmi:id="_oaadQrJFEeq_W6pXnlyepA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1Hum8LJREeq_W6pXnlyepA" target="_1HrjoLJREeq_W6pXnlyepA" source="_7mVzAJE9EeqRyKCsP6SKxA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1HvOALJREeq_W6pXnlyepA"/>
        <condition xmi:type="expression:Expression" xmi:id="_1HvOAbJREeq_W6pXnlyepA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5qAfULJREeq_W6pXnlyepA" target="_5p38cLJREeq_W6pXnlyepA" source="_8ISfoLJREeq_W6pXnlyepA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5qAfUbJREeq_W6pXnlyepA"/>
        <condition xmi:type="expression:Expression" xmi:id="_5qAfUrJREeq_W6pXnlyepA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7Q3IYLJREeq_W6pXnlyepA" target="_8ISfoLJREeq_W6pXnlyepA" source="_1HrjoLJREeq_W6pXnlyepA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7Q3IYbJREeq_W6pXnlyepA"/>
        <condition xmi:type="expression:Expression" xmi:id="_7Q3IYrJREeq_W6pXnlyepA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TRCucLJTEeq_W6pXnlyepA" target="_6vzX0LJTEeq_W6pXnlyepA" source="_jpVwYLJEEeq_W6pXnlyepA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TRDVgLJTEeq_W6pXnlyepA"/>
        <condition xmi:type="expression:Expression" xmi:id="_TRDVgbJTEeq_W6pXnlyepA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UsYM4L08EeqGG6w3Dt49BQ" target="_NuRx0LJFEeq_W6pXnlyepA" source="_mFY_wL0_EeqGG6w3Dt49BQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UsYM4b08EeqGG6w3Dt49BQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_UsYM4r08EeqGG6w3Dt49BQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_c17t8L08EeqGG6w3Dt49BQ" target="_xfH0cLJEEeq_W6pXnlyepA" source="_8ISfoLJREeq_W6pXnlyepA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_c17t8b08EeqGG6w3Dt49BQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_c17t8r08EeqGG6w3Dt49BQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_d8vlAL08EeqGG6w3Dt49BQ" target="_-i0JsLJDEeq_W6pXnlyepA" source="_SmmPUL1AEeqGG6w3Dt49BQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_d8vlAb08EeqGG6w3Dt49BQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_d8vlAr08EeqGG6w3Dt49BQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iqo3gL08EeqGG6w3Dt49BQ" target="_DRCzYLJEEeq_W6pXnlyepA" source="_-i0JsLJDEeq_W6pXnlyepA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_iqo3gb08EeqGG6w3Dt49BQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_iqo3gr08EeqGG6w3Dt49BQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__YpUEL08EeqGG6w3Dt49BQ" target="_AaWBoL09EeqGG6w3Dt49BQ" source="_oaTvkLJFEeq_W6pXnlyepA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__Yp7IL08EeqGG6w3Dt49BQ"/>
        <condition xmi:type="expression:Expression" xmi:id="__Yp7Ib08EeqGG6w3Dt49BQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BcNuUL09EeqGG6w3Dt49BQ" target="_jpVwYLJEEeq_W6pXnlyepA" source="_AaWBoL09EeqGG6w3Dt49BQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BcNuUb09EeqGG6w3Dt49BQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_BcNuUr09EeqGG6w3Dt49BQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CAankL09EeqGG6w3Dt49BQ" target="_DRCzYLJEEeq_W6pXnlyepA" source="_AaWBoL09EeqGG6w3Dt49BQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CAankb09EeqGG6w3Dt49BQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_CAankr09EeqGG6w3Dt49BQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SmpSoL1AEeqGG6w3Dt49BQ" target="_SmmPUL1AEeqGG6w3Dt49BQ" source="_xfH0cLJEEeq_W6pXnlyepA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Smp5sL1AEeqGG6w3Dt49BQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Smp5sb1AEeqGG6w3Dt49BQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_WMg145E9EeqRyKCsP6SKxA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_WMg10JE9EeqRyKCsP6SKxA">
        <name xmi:type="expression:Expression" xmi:id="_WMg10ZE9EeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_WMg10pE9EeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_WMg105E9EeqRyKCsP6SKxA">
        <name xmi:type="expression:Expression" xmi:id="_WMg11JE9EeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_WMg11ZE9EeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_WMg11pE9EeqRyKCsP6SKxA">
        <name xmi:type="expression:Expression" xmi:id="_WMg115E9EeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_WMg12JE9EeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_WMg12ZE9EeqRyKCsP6SKxA">
        <name xmi:type="expression:Expression" xmi:id="_WMg12pE9EeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_WMg125E9EeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_WMg13JE9EeqRyKCsP6SKxA">
        <name xmi:type="expression:Expression" xmi:id="_WMg13ZE9EeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_WMg13pE9EeqRyKCsP6SKxA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_VGz2YJFbEeqFN64BkO7kBw" name="Resource Allocation">
      <elements xmi:type="process:Lane" xmi:id="_WH0AYJFbEeqFN64BkO7kBw" name="Lane1"/>
      <formMapping xmi:type="process:FormMapping" xmi:id="_VG1rn5FbEeqFN64BkO7kBw">
        <targetForm xmi:type="expression:Expression" xmi:id="_VG1roJFbEeqFN64BkO7kBw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_VG1roZFbEeqFN64BkO7kBw">
        <targetForm xmi:type="expression:Expression" xmi:id="_VG1ropFbEeqFN64BkO7kBw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <contract xmi:type="process:Contract" xmi:id="_VG1ro5FbEeqFN64BkO7kBw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_VG1rkJFbEeqFN64BkO7kBw">
        <name xmi:type="expression:Expression" xmi:id="_VG1rkZFbEeqFN64BkO7kBw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_VG1rkpFbEeqFN64BkO7kBw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_VG1rk5FbEeqFN64BkO7kBw">
        <name xmi:type="expression:Expression" xmi:id="_VG1rlJFbEeqFN64BkO7kBw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_VG1rlZFbEeqFN64BkO7kBw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_VG1rlpFbEeqFN64BkO7kBw">
        <name xmi:type="expression:Expression" xmi:id="_VG1rl5FbEeqFN64BkO7kBw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_VG1rmJFbEeqFN64BkO7kBw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_VG1rmZFbEeqFN64BkO7kBw">
        <name xmi:type="expression:Expression" xmi:id="_VG1rmpFbEeqFN64BkO7kBw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_VG1rm5FbEeqFN64BkO7kBw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_VG1rnJFbEeqFN64BkO7kBw">
        <name xmi:type="expression:Expression" xmi:id="_VG1rnZFbEeqFN64BkO7kBw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_VG1rnpFbEeqFN64BkO7kBw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_5phsQJxaEeqp0LuU99oBBQ" name="Simulation">
      <elements xmi:type="process:StartSignalEvent" xmi:id="_9lxfYJxaEeqp0LuU99oBBQ" name="Start" outgoing="_EFZ1QJxbEeqp0LuU99oBBQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_9lyGcJxaEeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_9lxfYZxaEeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_9lyGcZxaEeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:IntermediateThrowMessageEvent" xmi:id="_EFSggJxbEeqp0LuU99oBBQ" name="Simulated decision" outgoing="_dJQUQJxbEeqp0LuU99oBBQ" incoming="_EFZ1QJxbEeqp0LuU99oBBQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_EFTHkZxbEeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_EFTHkJxbEeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_EFTHkpxbEeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_dJN4AJxbEeqp0LuU99oBBQ" name="Present simulation results" outgoing="_oQWkgJxbEeqp0LuU99oBBQ" incoming="_dJQUQJxbEeqp0LuU99oBBQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_dJOfEZxbEeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_dJOfEJxbEeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_dJOfEpxbEeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_dJOfE5xbEeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_dJOfFJxbEeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dJOfFZxbEeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_dJOfF5xbEeqp0LuU99oBBQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_dJOfFpxbEeqp0LuU99oBBQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_oQUIQJxbEeqp0LuU99oBBQ" name="End2" incoming="_oQWkgJxbEeqp0LuU99oBBQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_oQUvUZxbEeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_oQUvUJxbEeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_oQUvUpxbEeqp0LuU99oBBQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_5pjhf5xaEeqp0LuU99oBBQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_5pjhgJxaEeqp0LuU99oBBQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_5pjhgZxaEeqp0LuU99oBBQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_5pjhgpxaEeqp0LuU99oBBQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EFZ1QJxbEeqp0LuU99oBBQ" target="_EFSggJxbEeqp0LuU99oBBQ" source="_9lxfYJxaEeqp0LuU99oBBQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EFZ1QZxbEeqp0LuU99oBBQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_EFZ1QpxbEeqp0LuU99oBBQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dJQUQJxbEeqp0LuU99oBBQ" target="_dJN4AJxbEeqp0LuU99oBBQ" source="_EFSggJxbEeqp0LuU99oBBQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dJQUQZxbEeqp0LuU99oBBQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_dJQUQpxbEeqp0LuU99oBBQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oQWkgJxbEeqp0LuU99oBBQ" target="_oQUIQJxbEeqp0LuU99oBBQ" source="_dJN4AJxbEeqp0LuU99oBBQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oQWkgZxbEeqp0LuU99oBBQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_oQWkgpxbEeqp0LuU99oBBQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_5pkIgJxaEeqp0LuU99oBBQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5pjhcJxaEeqp0LuU99oBBQ">
        <name xmi:type="expression:Expression" xmi:id="_5pjhcZxaEeqp0LuU99oBBQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5pjhcpxaEeqp0LuU99oBBQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5pjhc5xaEeqp0LuU99oBBQ">
        <name xmi:type="expression:Expression" xmi:id="_5pjhdJxaEeqp0LuU99oBBQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5pjhdZxaEeqp0LuU99oBBQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5pjhdpxaEeqp0LuU99oBBQ">
        <name xmi:type="expression:Expression" xmi:id="_5pjhd5xaEeqp0LuU99oBBQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5pjheJxaEeqp0LuU99oBBQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5pjheZxaEeqp0LuU99oBBQ">
        <name xmi:type="expression:Expression" xmi:id="_5pjhepxaEeqp0LuU99oBBQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5pjhe5xaEeqp0LuU99oBBQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5pjhfJxaEeqp0LuU99oBBQ">
        <name xmi:type="expression:Expression" xmi:id="_5pjhfZxaEeqp0LuU99oBBQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5pjhfpxaEeqp0LuU99oBBQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_dTk9HJEuEeqRyKCsP6SKxA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_dTk9HZEuEeqRyKCsP6SKxA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_dTk9HpEuEeqRyKCsP6SKxA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_dTk9H5EuEeqRyKCsP6SKxA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_dTk9IJEuEeqRyKCsP6SKxA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_dTk9IZEuEeqRyKCsP6SKxA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_dTk9IpEuEeqRyKCsP6SKxA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_dTk9I5EuEeqRyKCsP6SKxA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_dTk9JJEuEeqRyKCsP6SKxA" name="Business_Object"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_NDGk0JE-EeqRyKCsP6SKxA" name="Autonomous Decision" target="_6ZlE8JE9EeqRyKCsP6SKxA" source="_y5dY4JExEeqRyKCsP6SKxA"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_6RTgcJFCEeqYebkRM8FsyA" name="HumanAssistedDecisionMessage" target="_66v4UJE9EeqRyKCsP6SKxA" source="_zqX4cJExEeqRyKCsP6SKxA"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_AqkIkJFDEeqYebkRM8FsyA" name="HumanDecisionMessage" target="_7mVzAJE9EeqRyKCsP6SKxA" source="_0ijdoJExEeqRyKCsP6SKxA"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_dTk9JZEuEeqRyKCsP6SKxA" type="Process" element="_dTk88JEuEeqRyKCsP6SKxA" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_dTk9JpEuEeqRyKCsP6SKxA" type="2007" element="_dTk88ZEuEeqRyKCsP6SKxA">
      <children xmi:type="notation:DecorationNode" xmi:id="_dTk9J5EuEeqRyKCsP6SKxA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_dTk9KJEuEeqRyKCsP6SKxA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_dTk9KZEuEeqRyKCsP6SKxA" type="3007" element="_dTk88pEuEeqRyKCsP6SKxA">
          <children xmi:type="notation:DecorationNode" xmi:id="_dTk9KpEuEeqRyKCsP6SKxA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_dTk9K5EuEeqRyKCsP6SKxA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_e_FnEJEvEeqRyKCsP6SKxA" type="3012" element="_e_EY8JEvEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_e_FnEpEvEeqRyKCsP6SKxA" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_e_FnE5EvEeqRyKCsP6SKxA" x="2" y="10"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_e_FnEZEvEeqRyKCsP6SKxA" x="60" y="117" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_P356qZExEeqRyKCsP6SKxA" type="3027" element="_P356oJExEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_P36hsJExEeqRyKCsP6SKxA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_P356qpExEeqRyKCsP6SKxA" x="133" y="109" width="98" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_sJqgEJExEeqRyKCsP6SKxA" type="3008" element="_sJp5AJExEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_sJqgEpExEeqRyKCsP6SKxA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_sJqgE5ExEeqRyKCsP6SKxA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sJqgEZExEeqRyKCsP6SKxA" x="582" y="112" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_y5d_8JExEeqRyKCsP6SKxA" type="3011" element="_y5dY4JExEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_y5d_8pExEeqRyKCsP6SKxA" type="5028">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_y5d_85ExEeqRyKCsP6SKxA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_y5d_8ZExEeqRyKCsP6SKxA" x="725" y="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zqYfgJExEeqRyKCsP6SKxA" type="3011" element="_zqX4cJExEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_zqYfgpExEeqRyKCsP6SKxA" type="5028">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_zqYfg5ExEeqRyKCsP6SKxA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zqYfgZExEeqRyKCsP6SKxA" x="729" y="125"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0ikEsJExEeqRyKCsP6SKxA" type="3011" element="_0ijdoJExEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_0ikEspExEeqRyKCsP6SKxA" type="5028">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0ikEs5ExEeqRyKCsP6SKxA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0ikEsZExEeqRyKCsP6SKxA" x="763" y="225"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SSRO0JEyEeqRyKCsP6SKxA" type="3027" element="_SSQnwJEyEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SSRO0pEyEeqRyKCsP6SKxA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SSRO0ZEyEeqRyKCsP6SKxA" x="272" y="107" width="89" height="45"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_f1aDt5EyEeqRyKCsP6SKxA" type="3028" element="_f1ZcoJEyEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_f1aDuZEyEeqRyKCsP6SKxA" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f1aDuJEyEeqRyKCsP6SKxA" x="402" y="109" width="92" height="46"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_kTVAgJEyEeqRyKCsP6SKxA" type="3015" element="_kTUZcJEyEeqRyKCsP6SKxA">
              <children xmi:type="notation:DecorationNode" xmi:id="_kTVAhZEyEeqRyKCsP6SKxA" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_kTVAgZEyEeqRyKCsP6SKxA"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_kTVAgpEyEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_kTVAg5EyEeqRyKCsP6SKxA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kTVAhJEyEeqRyKCsP6SKxA" x="371" y="12" width="239"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_xs_64JEzEeqRyKCsP6SKxA" type="3015" element="_xs_T0JEzEeqRyKCsP6SKxA">
              <children xmi:type="notation:DecorationNode" xmi:id="_xs_65ZEzEeqRyKCsP6SKxA" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_xs_64ZEzEeqRyKCsP6SKxA"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_xs_64pEzEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_xs_645EzEeqRyKCsP6SKxA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xs_65JEzEeqRyKCsP6SKxA" x="175" y="180" width="325" height="86"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_SSXqkJE0EeqRyKCsP6SKxA" type="3015" element="_SSXDgJE0EeqRyKCsP6SKxA">
              <children xmi:type="notation:DecorationNode" xmi:id="_SSXqlZE0EeqRyKCsP6SKxA" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_SSXqkZE0EeqRyKCsP6SKxA"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_SSXqkpE0EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_SSXqk5E0EeqRyKCsP6SKxA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SSXqlJE0EeqRyKCsP6SKxA" x="89" y="18" width="184"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_R3_bY5xbEeqp0LuU99oBBQ" type="3013" element="_R3-0UJxbEeqp0LuU99oBBQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_R4ACcJxbEeqp0LuU99oBBQ" type="5027">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_R4ACcZxbEeqp0LuU99oBBQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_R3_bZJxbEeqp0LuU99oBBQ" x="72" y="225"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_dTk9M5EuEeqRyKCsP6SKxA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_dTk9NJEuEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_dTk9NZEuEeqRyKCsP6SKxA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_dTk9NpEuEeqRyKCsP6SKxA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dTk9N5EuEeqRyKCsP6SKxA" x="44" y="10" width="1263" height="355"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_lp0ncZE0EeqRyKCsP6SKxA" type="3007" element="_lp0ncJE0EeqRyKCsP6SKxA">
          <children xmi:type="notation:DecorationNode" xmi:id="_lp1OgJE0EeqRyKCsP6SKxA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_lp1OgZE0EeqRyKCsP6SKxA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_7gVnwJE0EeqRyKCsP6SKxA" type="3016" element="_7gVAsJE0EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_7gVnwpE0EeqRyKCsP6SKxA" type="5031">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_7gVnw5E0EeqRyKCsP6SKxA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7gVnwZE0EeqRyKCsP6SKxA" x="72" y="126"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_hs8swJE1EeqRyKCsP6SKxA" type="3005" element="_hs8FsJE1EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_hs8swpE1EeqRyKCsP6SKxA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hs8swZE1EeqRyKCsP6SKxA" x="357" y="61" width="130" height="65"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tGvPgJE1EeqRyKCsP6SKxA" type="3027" element="_tGuocJE1EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tGvPgpE1EeqRyKCsP6SKxA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tGvPgZE1EeqRyKCsP6SKxA" x="355" y="178" width="134" height="67"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kMTuU5E5EeqRyKCsP6SKxA" type="3009" element="_kMTHQJE5EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_kMTuVZE5EeqRyKCsP6SKxA" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_kMTuVpE5EeqRyKCsP6SKxA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kMTuVJE5EeqRyKCsP6SKxA" x="553" y="119"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_lIzy0JE5EeqRyKCsP6SKxA" type="3009" element="_lIzLwJE5EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_lIzy0pE5EeqRyKCsP6SKxA" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_lIzy05E5EeqRyKCsP6SKxA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lIzy0ZE5EeqRyKCsP6SKxA" x="287" y="125" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_G1PRMJE6EeqRyKCsP6SKxA" type="3027" element="_G1OqIJE6EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_G1PRMpE6EeqRyKCsP6SKxA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_G1PRMZE6EeqRyKCsP6SKxA" x="763" y="111" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_L5EXeJE6EeqRyKCsP6SKxA" type="3028" element="_L5DwYJE6EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_L5EXepE6EeqRyKCsP6SKxA" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_L5EXeZE6EeqRyKCsP6SKxA" x="623" y="113" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_oPhkwJE8EeqRyKCsP6SKxA" type="3003" element="_oPfIgJE8EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_oPhkwpE8EeqRyKCsP6SKxA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_oPhkw5E8EeqRyKCsP6SKxA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oPhkwZE8EeqRyKCsP6SKxA" x="931" y="122"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_1Ex_8JE8EeqRyKCsP6SKxA" type="3015" element="_1ExY4JE8EeqRyKCsP6SKxA">
              <children xmi:type="notation:DecorationNode" xmi:id="_1Ex_9ZE8EeqRyKCsP6SKxA" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_1Ex_8ZE8EeqRyKCsP6SKxA"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_1Ex_8pE8EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_1Ex_85E8EeqRyKCsP6SKxA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1Ex_9JE8EeqRyKCsP6SKxA" x="119" y="209" width="94" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_y16f4JxZEeqp0LuU99oBBQ" type="3027" element="_y1540JxZEeqp0LuU99oBBQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_y16f4pxZEeqp0LuU99oBBQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_y16f4ZxZEeqp0LuU99oBBQ" x="161" y="116" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PC7vRJxaEeqp0LuU99oBBQ" type="3012" element="_PC7vQJxaEeqp0LuU99oBBQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_PC7vRpxaEeqp0LuU99oBBQ" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_PC7vR5xaEeqp0LuU99oBBQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PC7vRZxaEeqp0LuU99oBBQ" x="63" y="48" width="30" height="30"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_lp0ncpE0EeqRyKCsP6SKxA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_lp0nc5E0EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_lp0ndJE0EeqRyKCsP6SKxA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_lp1OgpE0EeqRyKCsP6SKxA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lp0ndZE0EeqRyKCsP6SKxA" x="44" y="293" width="1263" height="346"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_dTk9OJEuEeqRyKCsP6SKxA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_dTk9OZEuEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_dTk9OpEuEeqRyKCsP6SKxA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_dTk9O5EuEeqRyKCsP6SKxA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dTk9PJEuEeqRyKCsP6SKxA" width="1282" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_WMhc4JE9EeqRyKCsP6SKxA" type="2007" element="_WMgOwJE9EeqRyKCsP6SKxA">
      <children xmi:type="notation:DecorationNode" xmi:id="_WMhc5ZE9EeqRyKCsP6SKxA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_WMhc5pE9EeqRyKCsP6SKxA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_ctLGcJE9EeqRyKCsP6SKxA" type="3007" element="_ctKfYJE9EeqRyKCsP6SKxA">
          <children xmi:type="notation:DecorationNode" xmi:id="_ctLGdZE9EeqRyKCsP6SKxA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_ctLGdpE9EeqRyKCsP6SKxA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_6ZlsAJE9EeqRyKCsP6SKxA" type="3012" element="_6ZlE8JE9EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_6ZlsApE9EeqRyKCsP6SKxA" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_6ZlsA5E9EeqRyKCsP6SKxA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6ZlsAZE9EeqRyKCsP6SKxA" x="61" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5w_pMJw5Eeqp0LuU99oBBQ" type="3028" element="_5wtVUJw5Eeqp0LuU99oBBQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5xAQQJw5Eeqp0LuU99oBBQ" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5w_pMZw5Eeqp0LuU99oBBQ" x="193" y="99" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_7LsFkJw5Eeqp0LuU99oBBQ" type="3028" element="_7Lq3cJw5Eeqp0LuU99oBBQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_7LsFkpw5Eeqp0LuU99oBBQ" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7LsFkZw5Eeqp0LuU99oBBQ" x="554" y="99" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_73T1cJw5Eeqp0LuU99oBBQ" type="3028" element="_73SnUJw5Eeqp0LuU99oBBQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_73T1cpw5Eeqp0LuU99oBBQ" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_73T1cZw5Eeqp0LuU99oBBQ" x="375" y="95" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_DNicIJw6Eeqp0LuU99oBBQ" type="3011" element="_DNhOAJw6Eeqp0LuU99oBBQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_DNicIpw6Eeqp0LuU99oBBQ" type="5028">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_DNicI5w6Eeqp0LuU99oBBQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DNicIZw6Eeqp0LuU99oBBQ" x="762" y="112"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_ctLGcZE9EeqRyKCsP6SKxA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_ctLGcpE9EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_ctLGc5E9EeqRyKCsP6SKxA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_ctLGd5E9EeqRyKCsP6SKxA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ctLGdJE9EeqRyKCsP6SKxA" x="115" y="58"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_gHobIJE9EeqRyKCsP6SKxA" type="3007" element="_gHn0EJE9EeqRyKCsP6SKxA">
          <children xmi:type="notation:DecorationNode" xmi:id="_gHobJZE9EeqRyKCsP6SKxA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_gHpCMJE9EeqRyKCsP6SKxA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_66wfY5E9EeqRyKCsP6SKxA" type="3012" element="_66v4UJE9EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_66wfZZE9EeqRyKCsP6SKxA" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_66wfZpE9EeqRyKCsP6SKxA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_66wfZJE9EeqRyKCsP6SKxA" x="67" y="105"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_pmONw5FDEeqYebkRM8FsyA" type="3028" element="_pmNmsJFDEeqYebkRM8FsyA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pmONxZFDEeqYebkRM8FsyA" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pmONxJFDEeqYebkRM8FsyA" x="189" y="69" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qsZytJFDEeqYebkRM8FsyA" type="3028" element="_qsZLoJFDEeqYebkRM8FsyA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qsZytpFDEeqYebkRM8FsyA" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qsZytZFDEeqYebkRM8FsyA" x="376" y="72" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zU22RJFDEeqYebkRM8FsyA" type="3028" element="_zU2PMJFDEeqYebkRM8FsyA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zU22RpFDEeqYebkRM8FsyA" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zU22RZFDEeqYebkRM8FsyA" x="692" y="73" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_3eWbMJFDEeqYebkRM8FsyA" type="3011" element="_3eV0IJFDEeqYebkRM8FsyA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_3eWbMpFDEeqYebkRM8FsyA" type="5028">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_3eWbM5FDEeqYebkRM8FsyA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3eWbMZFDEeqYebkRM8FsyA" x="861" y="87"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_K0HzAJw6Eeqp0LuU99oBBQ" type="3005" element="_K0F90Jw6Eeqp0LuU99oBBQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_K0HzApw6Eeqp0LuU99oBBQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_K0HzAZw6Eeqp0LuU99oBBQ" x="525" y="69" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_gHobIZE9EeqRyKCsP6SKxA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_gHobIpE9EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_gHobI5E9EeqRyKCsP6SKxA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_gHpCMZE9EeqRyKCsP6SKxA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gHobJJE9EeqRyKCsP6SKxA" x="103" y="185"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_gZYScJE9EeqRyKCsP6SKxA" type="3007" element="_gZXrYJE9EeqRyKCsP6SKxA">
          <children xmi:type="notation:DecorationNode" xmi:id="_gZYSdZE9EeqRyKCsP6SKxA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_gZYSdpE9EeqRyKCsP6SKxA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_7mWaE5E9EeqRyKCsP6SKxA" type="3012" element="_7mVzAJE9EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_7mWaFZE9EeqRyKCsP6SKxA" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_7mWaFpE9EeqRyKCsP6SKxA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7mWaFJE9EeqRyKCsP6SKxA" x="168" y="51"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HR1iGJFEEeqYebkRM8FsyA" type="3028" element="_HR07AJFEEeqYebkRM8FsyA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_HR2JIJFEEeqYebkRM8FsyA" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HR1iGZFEEeqYebkRM8FsyA" x="1143" y="404" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_J1ubIpFEEeqYebkRM8FsyA" type="3011" element="_J1t0EJFEEeqYebkRM8FsyA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_J1ubJJFEEeqYebkRM8FsyA" type="5028">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_J1vCMJFEEeqYebkRM8FsyA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_J1ubI5FEEeqYebkRM8FsyA" x="1323" y="415"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-i0wwLJDEeq_W6pXnlyepA" type="3027" element="_-i0JsLJDEeq_W6pXnlyepA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-i0wwrJDEeq_W6pXnlyepA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-i0wwbJDEeq_W6pXnlyepA" x="69" y="462" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_DREBgLJEEeq_W6pXnlyepA" type="3027" element="_DRCzYLJEEeq_W6pXnlyepA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_DREBgrJEEeq_W6pXnlyepA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DREBgbJEEeq_W6pXnlyepA" x="73" y="540" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jpW-gLJEEeq_W6pXnlyepA" type="3027" element="_jpVwYLJEEeq_W6pXnlyepA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_jpW-grJEEeq_W6pXnlyepA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jpW-gbJEEeq_W6pXnlyepA" x="408" y="540" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xfIbiLJEEeq_W6pXnlyepA" type="3027" element="_xfH0cLJEEeq_W6pXnlyepA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xfJCkLJEEeq_W6pXnlyepA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xfIbibJEEeq_W6pXnlyepA" x="63" y="312" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8_IT8LJEEeq_W6pXnlyepA" type="3017" element="_8_Hs4LJEEeq_W6pXnlyepA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_8_I7ALJEEeq_W6pXnlyepA" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_8_I7AbJEEeq_W6pXnlyepA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8_IT8bJEEeq_W6pXnlyepA" x="931" y="419"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NRyqILJFEeq_W6pXnlyepA" type="3028" element="_NRxcALJFEeq_W6pXnlyepA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_NRyqIrJFEeq_W6pXnlyepA" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NRyqIbJFEeq_W6pXnlyepA" x="1001" y="404" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NuSY6LJFEeq_W6pXnlyepA" type="3028" element="_NuRx0LJFEeq_W6pXnlyepA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_NuSY6rJFEeq_W6pXnlyepA" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NuSY6bJFEeq_W6pXnlyepA" x="753" y="399" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_oaUWoLJFEeq_W6pXnlyepA" type="3017" element="_oaTvkLJFEeq_W6pXnlyepA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_oaUWorJFEeq_W6pXnlyepA" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_oaUWo7JFEeq_W6pXnlyepA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oaUWobJFEeq_W6pXnlyepA" x="258" y="554"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_WSCMgLJOEeq_W6pXnlyepA" type="3015" element="_WSBlcLJOEeq_W6pXnlyepA">
              <children xmi:type="notation:DecorationNode" xmi:id="_WSCMhbJOEeq_W6pXnlyepA" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_WSCMgbJOEeq_W6pXnlyepA"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_WSCMgrJOEeq_W6pXnlyepA" fontName=".AppleSystemUIFont"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_WSCMg7JOEeq_W6pXnlyepA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WSCMhLJOEeq_W6pXnlyepA" x="368" y="10" width="407" height="265"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1HsxwLJREeq_W6pXnlyepA" type="3027" element="_1HrjoLJREeq_W6pXnlyepA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_1HsxwrJREeq_W6pXnlyepA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1HsxwbJREeq_W6pXnlyepA" x="106" y="134" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5p5KkLJREeq_W6pXnlyepA" type="3011" element="_5p38cLJREeq_W6pXnlyepA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_5p5KkrJREeq_W6pXnlyepA" type="5028">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5p5Kk7JREeq_W6pXnlyepA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5p5KkbJREeq_W6pXnlyepA" x="245" y="274"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8ITGsrJREeq_W6pXnlyepA" type="3008" element="_8ISfoLJREeq_W6pXnlyepA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_8ITGtLJREeq_W6pXnlyepA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_8ITGtbJREeq_W6pXnlyepA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8ITGs7JREeq_W6pXnlyepA" x="126" y="219" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6vzX3bJTEeq_W6pXnlyepA" type="3005" element="_6vzX0LJTEeq_W6pXnlyepA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_6vz-4LJTEeq_W6pXnlyepA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6vzX3rJTEeq_W6pXnlyepA" x="554" y="540" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_UzFrIL03EeqGG6w3Dt49BQ" type="3015" element="_Uy-9cL03EeqGG6w3Dt49BQ">
              <children xmi:type="notation:DecorationNode" xmi:id="_UzGSML03EeqGG6w3Dt49BQ" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_UzFrIb03EeqGG6w3Dt49BQ"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_UzFrIr03EeqGG6w3Dt49BQ" fontName=".AppleSystemUIFont"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_UzFrI703EeqGG6w3Dt49BQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UzFrJL03EeqGG6w3Dt49BQ" x="245" y="191"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_DkqTcL07EeqGG6w3Dt49BQ" type="3015" element="_DkpsYL07EeqGG6w3Dt49BQ">
              <children xmi:type="notation:DecorationNode" xmi:id="_DkqTdb07EeqGG6w3Dt49BQ" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_DkqTcb07EeqGG6w3Dt49BQ"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_DkqTcr07EeqGG6w3Dt49BQ" fontName=".AppleSystemUIFont"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_DkqTc707EeqGG6w3Dt49BQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DkqTdL07EeqGG6w3Dt49BQ" x="264" y="336" width="169"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_AaWos709EeqGG6w3Dt49BQ" type="3008" element="_AaWBoL09EeqGG6w3Dt49BQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_AaWotb09EeqGG6w3Dt49BQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_AaWotr09EeqGG6w3Dt49BQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AaWotL09EeqGG6w3Dt49BQ" x="323" y="548" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_mFZm2b0_EeqGG6w3Dt49BQ" type="3005" element="_mFY_wL0_EeqGG6w3Dt49BQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_mFZm270_EeqGG6w3Dt49BQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mFZm2r0_EeqGG6w3Dt49BQ" x="552" y="408" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SmndcL1AEeqGG6w3Dt49BQ" type="3027" element="_SmmPUL1AEeqGG6w3Dt49BQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Smndcr1AEeqGG6w3Dt49BQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Smndcb1AEeqGG6w3Dt49BQ" x="83" y="397"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_gZYScZE9EeqRyKCsP6SKxA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_gZYScpE9EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_gZYSc5E9EeqRyKCsP6SKxA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_gZYSd5E9EeqRyKCsP6SKxA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gZYSdJE9EeqRyKCsP6SKxA" x="19" y="500" width="1466" height="760"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_WMhc4ZE9EeqRyKCsP6SKxA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_WMhc4pE9EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_WMhc45E9EeqRyKCsP6SKxA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_WMhc55E9EeqRyKCsP6SKxA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WMhc5JE9EeqRyKCsP6SKxA" width="1485" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_VG1rpJFbEeqFN64BkO7kBw" type="2007" element="_VGz2YJFbEeqFN64BkO7kBw">
      <children xmi:type="notation:DecorationNode" xmi:id="_VG1rqZFbEeqFN64BkO7kBw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_VG1rqpFbEeqFN64BkO7kBw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_WH0ncJFbEeqFN64BkO7kBw" type="3007" element="_WH0AYJFbEeqFN64BkO7kBw">
          <children xmi:type="notation:DecorationNode" xmi:id="_WH0ndZFbEeqFN64BkO7kBw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_WH0ndpFbEeqFN64BkO7kBw" type="7002"/>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_WH0ncZFbEeqFN64BkO7kBw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_WH0ncpFbEeqFN64BkO7kBw" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_WH0nc5FbEeqFN64BkO7kBw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_WH0nd5FbEeqFN64BkO7kBw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WH0ndJFbEeqFN64BkO7kBw" x="93" y="49"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_VG1rpZFbEeqFN64BkO7kBw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_VG1rppFbEeqFN64BkO7kBw" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_VG1rp5FbEeqFN64BkO7kBw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_VG1rq5FbEeqFN64BkO7kBw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VG1rqJFbEeqFN64BkO7kBw" width="840" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_5pkIgZxaEeqp0LuU99oBBQ" type="2007" element="_5phsQJxaEeqp0LuU99oBBQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_5pkvkJxaEeqp0LuU99oBBQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_5pkvkZxaEeqp0LuU99oBBQ" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_9lytgJxaEeqp0LuU99oBBQ" type="3023" element="_9lxfYJxaEeqp0LuU99oBBQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_9lytgpxaEeqp0LuU99oBBQ" type="5038">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_9lytg5xaEeqp0LuU99oBBQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9lytgZxaEeqp0LuU99oBBQ" x="103" y="95"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_EFTuoJxbEeqp0LuU99oBBQ" type="3014" element="_EFSggJxbEeqp0LuU99oBBQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_EFTuopxbEeqp0LuU99oBBQ" type="5030">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_EFTuo5xbEeqp0LuU99oBBQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EFTuoZxbEeqp0LuU99oBBQ" x="187" y="98"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_dJOfGJxbEeqp0LuU99oBBQ" type="3027" element="_dJN4AJxbEeqp0LuU99oBBQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_dJPGIZxbEeqp0LuU99oBBQ" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dJPGIJxbEeqp0LuU99oBBQ" x="308" y="80" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_oQVWYJxbEeqp0LuU99oBBQ" type="3003" element="_oQUIQJxbEeqp0LuU99oBBQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_oQVWYpxbEeqp0LuU99oBBQ" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_oQVWY5xbEeqp0LuU99oBBQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oQVWYZxbEeqp0LuU99oBBQ" x="587" y="95"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_5pkIgpxaEeqp0LuU99oBBQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_5pkIg5xaEeqp0LuU99oBBQ" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_5pkIhJxaEeqp0LuU99oBBQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_5pkvkpxaEeqp0LuU99oBBQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5pkIhZxaEeqp0LuU99oBBQ" width="840" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_dTk9PZEuEeqRyKCsP6SKxA"/>
    <edges xmi:type="notation:Connector" xmi:id="_dTk9PpEuEeqRyKCsP6SKxA" type="4001" element="_dTk9CJEuEeqRyKCsP6SKxA" source="_e_FnEJEvEeqRyKCsP6SKxA" target="_P356qZExEeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dTk9P5EuEeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dTk9QJEuEeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dTk9QZEuEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dTk9QpEuEeqRyKCsP6SKxA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qtQzgpExEeqRyKCsP6SKxA" type="4001" element="_qtQMcJExEeqRyKCsP6SKxA" source="_f1aDt5EyEeqRyKCsP6SKxA" target="_sJqgEJExEeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qtQzhZExEeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qtRakJExEeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qtQzg5ExEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qtQzhJExEeqRyKCsP6SKxA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WDMiwJEyEeqRyKCsP6SKxA" id="(0.97,0.36)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_y5nw85ExEeqRyKCsP6SKxA" type="4001" element="_y5nw8JExEeqRyKCsP6SKxA" source="_sJqgEJExEeqRyKCsP6SKxA" target="_y5d_8JExEeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_y5oYAJExEeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_y5oYAZExEeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_y5nw9JExEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_y5nw9ZExEeqRyKCsP6SKxA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7ujxUJExEeqRyKCsP6SKxA" id="(0.8372093023255814,0.20930232558139536)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UaLVgJE9EeqRyKCsP6SKxA" id="(0.03333333333333333,0.5666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zqhpcJExEeqRyKCsP6SKxA" type="4001" element="_zqd_EJExEeqRyKCsP6SKxA" source="_sJqgEJExEeqRyKCsP6SKxA" target="_zqYfgJExEeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zqiQgJExEeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zqiQgZExEeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zqhpcZExEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zqhpcpExEeqRyKCsP6SKxA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_147asJExEeqRyKCsP6SKxA" id="(0.9302325581395349,0.3953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0it1sJExEeqRyKCsP6SKxA" type="4001" element="_0ipkQJExEeqRyKCsP6SKxA" source="_sJqgEJExEeqRyKCsP6SKxA" target="_0ikEsJExEeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0it1s5ExEeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0it1tJExEeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0it1sZExEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0it1spExEeqRyKCsP6SKxA" points="[4, 2, -174, -86]$[65, 2, -113, -86]$[65, 73, -113, -15]$[173, 73, -5, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1XuyIJExEeqRyKCsP6SKxA" id="(0.4186046511627907,0.9302325581395349)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EGPxgLJOEeq_W6pXnlyepA" id="(0.03333333333333333,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SSU5MJEyEeqRyKCsP6SKxA" type="4001" element="_SSUSIJEyEeqRyKCsP6SKxA" source="_P356qZExEeqRyKCsP6SKxA" target="_SSRO0JEyEeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SSU5M5EyEeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SSU5NJEyEeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SSU5MZEyEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SSU5MpEyEeqRyKCsP6SKxA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dBTkYpEyEeqRyKCsP6SKxA" type="4001" element="_dBS9UJEyEeqRyKCsP6SKxA" source="_SSRO0JEyEeqRyKCsP6SKxA" target="_f1aDt5EyEeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dBTkZZEyEeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dBTkZpEyEeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dBTkY5EyEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dBTkZJEyEeqRyKCsP6SKxA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kTc8UJEyEeqRyKCsP6SKxA" type="4003" element="_kTcVQJEyEeqRyKCsP6SKxA" source="_kTVAgJEyEeqRyKCsP6SKxA" target="_f1aDt5EyEeqRyKCsP6SKxA">
      <styles xmi:type="notation:FontStyle" xmi:id="_kTc8UZEyEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kTc8UpEyEeqRyKCsP6SKxA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xtBwEZEzEeqRyKCsP6SKxA" type="4003" element="_xtBwEJEzEeqRyKCsP6SKxA" source="_xs_64JEzEeqRyKCsP6SKxA" target="_SSRO0JEyEeqRyKCsP6SKxA">
      <styles xmi:type="notation:FontStyle" xmi:id="_xtBwEpEzEeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xtBwE5EzEeqRyKCsP6SKxA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SSZfwZE0EeqRyKCsP6SKxA" type="4003" element="_SSZfwJE0EeqRyKCsP6SKxA" source="_SSXqkJE0EeqRyKCsP6SKxA" target="_P356qZExEeqRyKCsP6SKxA">
      <styles xmi:type="notation:FontStyle" xmi:id="_SSZfwpE0EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SSZfw5E0EeqRyKCsP6SKxA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Eb08EJE1EeqRyKCsP6SKxA" type="4001" element="_Eb0VAJE1EeqRyKCsP6SKxA" source="_7gVnwJE0EeqRyKCsP6SKxA" target="_y16f4JxZEeqp0LuU99oBBQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Eb08E5E1EeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Eb08FJE1EeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Eb08EZE1EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Eb08EpE1EeqRyKCsP6SKxA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_G-aNkJE1EeqRyKCsP6SKxA" type="4001" element="_G-ZmgJE1EeqRyKCsP6SKxA" source="_PC7vRJxaEeqp0LuU99oBBQ" target="_y16f4JxZEeqp0LuU99oBBQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_G-aNk5E1EeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_G-aNlJE1EeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_G-aNkZE1EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_G-aNkpE1EeqRyKCsP6SKxA" points="[0, -14, -111, -67]$[54, -14, -57, -67]$[54, 49, -57, -4]$[104, 49, -7, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_G-a0oJE1EeqRyKCsP6SKxA" id="(1.0,0.9666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_G-a0oZE1EeqRyKCsP6SKxA" id="(0.07,0.28)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_O9tmcJE1EeqRyKCsP6SKxA" type="4001" element="_O9s_YJE1EeqRyKCsP6SKxA" source="_lIzy0JE5EeqRyKCsP6SKxA" target="_hs8swJE1EeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_O9tmc5E1EeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_O9tmdJE1EeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_O9tmcZE1EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_O9tmcpE1EeqRyKCsP6SKxA" points="[1, 4, -53, 9]$[1, -44, -53, -39]$[43, -44, -11, -39]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_aiSc4JE1EeqRyKCsP6SKxA" id="(0.627906976744186,0.046511627906976744)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Qq8LAJE6EeqRyKCsP6SKxA" id="(0.08461538461538462,0.9384615384615385)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QvMLIpE1EeqRyKCsP6SKxA" type="4001" element="_QvLkEJE1EeqRyKCsP6SKxA" source="_y16f4JxZEeqp0LuU99oBBQ" target="_lIzy0JE5EeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QvMLJZE1EeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QvMLJpE1EeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QvMLI5E1EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QvMLJJE1EeqRyKCsP6SKxA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tG0vEJE1EeqRyKCsP6SKxA" type="4001" element="_tGxEsJE1EeqRyKCsP6SKxA" source="_lIzy0JE5EeqRyKCsP6SKxA" target="_tGvPgJE1EeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tG0vE5E1EeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tG0vFJE1EeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tG0vEZE1EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tG0vEpE1EeqRyKCsP6SKxA" points="[1, 21, -140, -44]$[49, 21, -92, -44]$[49, 32, -92, -33]$[74, 32, -67, -33]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kMWKkZE5EeqRyKCsP6SKxA" type="4001" element="_kMVjgJE5EeqRyKCsP6SKxA" source="_hs8swJE1EeqRyKCsP6SKxA" target="_kMTuU5E5EeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kMWKlJE5EeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kMWKlZE5EeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kMWKkpE5EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kMWKk5E5EeqRyKCsP6SKxA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_l0cw0pE5EeqRyKCsP6SKxA" type="4001" element="_l0cJwJE5EeqRyKCsP6SKxA" source="_tGvPgJE1EeqRyKCsP6SKxA" target="_kMTuU5E5EeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_l0cw1ZE5EeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_l0dX4JE5EeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_l0cw05E5EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_l0cw1JE5EeqRyKCsP6SKxA" points="[0, 0, -146, 76]$[126, -74, -20, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_l0d-8JE5EeqRyKCsP6SKxA" id="(1.0,0.4626865671641791)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_v3aDg5E5EeqRyKCsP6SKxA" type="4001" element="_v3aDgJE5EeqRyKCsP6SKxA" source="_kMTuU5E5EeqRyKCsP6SKxA" target="_L5EXeJE6EeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_v3aDhpE5EeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_v3aDh5E5EeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_v3aDhJE5EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_v3aDhZE5EeqRyKCsP6SKxA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_G1RGY5E6EeqRyKCsP6SKxA" type="4001" element="_G1RGYJE6EeqRyKCsP6SKxA" source="_L5EXeJE6EeqRyKCsP6SKxA" target="_G1PRMJE6EeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_G1RGZpE6EeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_G1RGZ5E6EeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_G1RGZJE6EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_G1RGZZE6EeqRyKCsP6SKxA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oPkBApE8EeqRyKCsP6SKxA" type="4001" element="_oPjZ8JE8EeqRyKCsP6SKxA" source="_G1PRMJE6EeqRyKCsP6SKxA" target="_oPhkwJE8EeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oPkBBZE8EeqRyKCsP6SKxA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oPkBBpE8EeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oPkBA5E8EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oPkBBJE8EeqRyKCsP6SKxA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1EzOEZE8EeqRyKCsP6SKxA" type="4003" element="_1EzOEJE8EeqRyKCsP6SKxA" source="_1Ex_8JE8EeqRyKCsP6SKxA" target="_y16f4JxZEeqp0LuU99oBBQ">
      <styles xmi:type="notation:FontStyle" xmi:id="_1EzOEpE8EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1EzOE5E8EeqRyKCsP6SKxA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NDHL4JE-EeqRyKCsP6SKxA" type="4002" element="_NDGk0JE-EeqRyKCsP6SKxA" source="_y5d_8JExEeqRyKCsP6SKxA" target="_6ZlsAJE9EeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NDHL45E-EeqRyKCsP6SKxA" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NDHL5JE-EeqRyKCsP6SKxA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NDHL4ZE-EeqRyKCsP6SKxA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NDHL4pE-EeqRyKCsP6SKxA" points="[10, 10, 674, -689]$[289, 10, 953, -689]$[289, 557, 953, -142]$[-666, 557, -2, -142]$[-666, 684, -2, -15]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zUVHQJFCEeqYebkRM8FsyA" type="4001" element="_zUT5IJFCEeqYebkRM8FsyA" source="_6ZlsAJE9EeqRyKCsP6SKxA" target="_5w_pMJw5Eeqp0LuU99oBBQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zUVuUJFCEeqYebkRM8FsyA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zUVuUZFCEeqYebkRM8FsyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zUVHQZFCEeqYebkRM8FsyA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zUVHQpFCEeqYebkRM8FsyA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6RUHgJFCEeqYebkRM8FsyA" type="4002" element="_6RTgcJFCEeqYebkRM8FsyA" source="_zqYfgJExEeqRyKCsP6SKxA" target="_66wfY5E9EeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6RUHg5FCEeqYebkRM8FsyA" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6RUHhJFCEeqYebkRM8FsyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6RUHgZFCEeqYebkRM8FsyA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6RUHgpFCEeqYebkRM8FsyA" points="[15, 0, 677, -889]$[271, 0, 933, -889]$[271, 782, 933, -107]$[-655, 782, 7, -107]$[-655, 875, 7, -14]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AqkvoJFDEeqYebkRM8FsyA" type="4002" element="_AqkIkJFDEeqYebkRM8FsyA" source="_0ikEsJExEeqRyKCsP6SKxA" target="_7mWaE5E9EeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Aqkvo5FDEeqYebkRM8FsyA" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AqkvpJFDEeqYebkRM8FsyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AqkvoZFDEeqYebkRM8FsyA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AqkvopFDEeqYebkRM8FsyA" points="[14, -1, 715, -1072]$[223, -1, 924, -1072]$[223, 957, 924, -114]$[-695, 957, 6, -114]$[-695, 1057, 6, -14]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_G-uOQJFDEeqYebkRM8FsyA" type="4001" element="_G-tnMJFDEeqYebkRM8FsyA" source="_66wfY5E9EeqRyKCsP6SKxA" target="_pmONw5FDEeqYebkRM8FsyA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_G-uOQ5FDEeqYebkRM8FsyA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_G-uORJFDEeqYebkRM8FsyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_G-uOQZFDEeqYebkRM8FsyA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_G-uOQpFDEeqYebkRM8FsyA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MHW8AJFDEeqYebkRM8FsyA" type="4001" element="_MHWU8JFDEeqYebkRM8FsyA" source="_pmONw5FDEeqYebkRM8FsyA" target="_qsZytJFDEeqYebkRM8FsyA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MHW8A5FDEeqYebkRM8FsyA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MHW8BJFDEeqYebkRM8FsyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MHW8AZFDEeqYebkRM8FsyA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MHW8ApFDEeqYebkRM8FsyA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_w1ge85FDEeqYebkRM8FsyA" type="4001" element="_w1ge8JFDEeqYebkRM8FsyA" source="_K0HzAJw6Eeqp0LuU99oBBQ" target="_zU22RJFDEeqYebkRM8FsyA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_w1hGAJFDEeqYebkRM8FsyA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_w1hGAZFDEeqYebkRM8FsyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_w1ge9JFDEeqYebkRM8FsyA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_w1ge9ZFDEeqYebkRM8FsyA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JWohUJw6Eeqp0LuU99oBBQ" id="(0.975,0.48333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3eb6wpFDEeqYebkRM8FsyA" type="4001" element="_3ebTsJFDEeqYebkRM8FsyA" source="_zU22RJFDEeqYebkRM8FsyA" target="_3eWbMJFDEeqYebkRM8FsyA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3eb6xZFDEeqYebkRM8FsyA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3eb6xpFDEeqYebkRM8FsyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3eb6w5FDEeqYebkRM8FsyA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3eb6xJFDEeqYebkRM8FsyA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Gk-cEJFEEeqYebkRM8FsyA" type="4001" element="_Gk91AJFEEeqYebkRM8FsyA" source="_NRyqILJFEeq_W6pXnlyepA" target="_HR1iGJFEEeqYebkRM8FsyA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Gk-cE5FEEeqYebkRM8FsyA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Gk-cFJFEEeqYebkRM8FsyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Gk-cEZFEEeqYebkRM8FsyA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Gk-cEpFEEeqYebkRM8FsyA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_J1z6sJFEEeqYebkRM8FsyA" type="4001" element="_J1zToJFEEeqYebkRM8FsyA" source="_HR1iGJFEEeqYebkRM8FsyA" target="_J1ubIpFEEeqYebkRM8FsyA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_J1z6s5FEEeqYebkRM8FsyA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_J1z6tJFEEeqYebkRM8FsyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_J1z6sZFEEeqYebkRM8FsyA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_J1z6spFEEeqYebkRM8FsyA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6WPrUJw5Eeqp0LuU99oBBQ" type="4001" element="_6WOdMJw5Eeqp0LuU99oBBQ" source="_5w_pMJw5Eeqp0LuU99oBBQ" target="_73T1cJw5Eeqp0LuU99oBBQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6WQSYJw5Eeqp0LuU99oBBQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6WQ5cJw5Eeqp0LuU99oBBQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6WPrUZw5Eeqp0LuU99oBBQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6WPrUpw5Eeqp0LuU99oBBQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6udXAJw5Eeqp0LuU99oBBQ" type="4001" element="_6ucv8Jw5Eeqp0LuU99oBBQ" source="_73T1cJw5Eeqp0LuU99oBBQ" target="_7LsFkJw5Eeqp0LuU99oBBQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6udXA5w5Eeqp0LuU99oBBQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6udXBJw5Eeqp0LuU99oBBQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6udXAZw5Eeqp0LuU99oBBQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6udXApw5Eeqp0LuU99oBBQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DNq_AZw6Eeqp0LuU99oBBQ" type="4001" element="_DNqX8Jw6Eeqp0LuU99oBBQ" source="_7LsFkJw5Eeqp0LuU99oBBQ" target="_DNicIJw6Eeqp0LuU99oBBQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DNq_BJw6Eeqp0LuU99oBBQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DNq_BZw6Eeqp0LuU99oBBQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DNq_Apw6Eeqp0LuU99oBBQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DNq_A5w6Eeqp0LuU99oBBQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Gk-5EJw6Eeqp0LuU99oBBQ" type="4001" element="_Gk-SAJw6Eeqp0LuU99oBBQ" source="_qsZytJFDEeqYebkRM8FsyA" target="_K0HzAJw6Eeqp0LuU99oBBQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Gk-5E5w6Eeqp0LuU99oBBQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Gk-5FJw6Eeqp0LuU99oBBQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Gk-5EZw6Eeqp0LuU99oBBQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Gk-5Epw6Eeqp0LuU99oBBQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EFZ1Q5xbEeqp0LuU99oBBQ" type="4001" element="_EFZ1QJxbEeqp0LuU99oBBQ" source="_9lytgJxaEeqp0LuU99oBBQ" target="_EFTuoJxbEeqp0LuU99oBBQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EFZ1RpxbEeqp0LuU99oBBQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EFZ1R5xbEeqp0LuU99oBBQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EFZ1RJxbEeqp0LuU99oBBQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EFZ1RZxbEeqp0LuU99oBBQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_S75vcpxbEeqp0LuU99oBBQ" type="4001" element="_S75IYJxbEeqp0LuU99oBBQ" source="_R3_bY5xbEeqp0LuU99oBBQ" target="_P356qZExEeqRyKCsP6SKxA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_S75vdZxbEeqp0LuU99oBBQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_S75vdpxbEeqp0LuU99oBBQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_S75vc5xbEeqp0LuU99oBBQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_S75vdJxbEeqp0LuU99oBBQ" points="[-5, -23, -103, 97]$[48, -115, -50, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_S769kJxbEeqp0LuU99oBBQ" id="(1.0,0.9)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dJQ7UJxbEeqp0LuU99oBBQ" type="4001" element="_dJQUQJxbEeqp0LuU99oBBQ" source="_EFTuoJxbEeqp0LuU99oBBQ" target="_dJOfGJxbEeqp0LuU99oBBQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dJQ7U5xbEeqp0LuU99oBBQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dJQ7VJxbEeqp0LuU99oBBQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dJQ7UZxbEeqp0LuU99oBBQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dJQ7UpxbEeqp0LuU99oBBQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oQWkg5xbEeqp0LuU99oBBQ" type="4001" element="_oQWkgJxbEeqp0LuU99oBBQ" source="_dJOfGJxbEeqp0LuU99oBBQ" target="_oQVWYJxbEeqp0LuU99oBBQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oQWkhpxbEeqp0LuU99oBBQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oQWkh5xbEeqp0LuU99oBBQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oQWkhJxbEeqp0LuU99oBBQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oQWkhZxbEeqp0LuU99oBBQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pqgBkrJEEeq_W6pXnlyepA" type="4001" element="_pqfagLJEEeq_W6pXnlyepA" source="_6vzX3bJTEeq_W6pXnlyepA" target="_mFZm2b0_EeqGG6w3Dt49BQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pqgBlbJEEeq_W6pXnlyepA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pqgBlrJEEeq_W6pXnlyepA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pqgBk7JEEeq_W6pXnlyepA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pqgBlLJEEeq_W6pXnlyepA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2wfpoLJTEeq_W6pXnlyepA" id="(0.9583333333333334,0.3)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_9R5hILJTEeq_W6pXnlyepA" id="(0.07142857142857142,0.4857142857142857)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8_T6ILJEEeq_W6pXnlyepA" type="4001" element="_8_TTELJEEeq_W6pXnlyepA" source="_NuSY6LJFEeq_W6pXnlyepA" target="_8_IT8LJEEeq_W6pXnlyepA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8_T6I7JEEeq_W6pXnlyepA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8_T6JLJEEeq_W6pXnlyepA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8_T6IbJEEeq_W6pXnlyepA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8_T6IrJEEeq_W6pXnlyepA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-qr20LJEEeq_W6pXnlyepA" type="4001" element="_-qrPwLJEEeq_W6pXnlyepA" source="_8_IT8LJEEeq_W6pXnlyepA" target="_NRyqILJFEeq_W6pXnlyepA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-qr207JEEeq_W6pXnlyepA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-qr21LJEEeq_W6pXnlyepA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-qr20bJEEeq_W6pXnlyepA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-qr20rJEEeq_W6pXnlyepA" points="[-15, -29, 137, 74]$[-15, -103, 137, 0]$[-92, -103, 60, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-qsd4LJEEeq_W6pXnlyepA" id="(1.0,0.9666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oabEULJFEeq_W6pXnlyepA" type="4001" element="_oaadQLJFEeq_W6pXnlyepA" source="_DREBgLJEEeq_W6pXnlyepA" target="_oaUWoLJFEeq_W6pXnlyepA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oabEU7JFEeq_W6pXnlyepA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oabEVLJFEeq_W6pXnlyepA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oabEUbJFEeq_W6pXnlyepA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oabEUrJFEeq_W6pXnlyepA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WuhUMLJOEeq_W6pXnlyepA" type="4003" element="_WugtILJOEeq_W6pXnlyepA" source="_WSCMgLJOEeq_W6pXnlyepA" target="_1HsxwLJREeq_W6pXnlyepA">
      <styles xmi:type="notation:FontStyle" xmi:id="_WuhUMbJOEeq_W6pXnlyepA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WuhUMrJOEeq_W6pXnlyepA" points="[-100, 9, 106, 0]$[-202, 6, 4, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WuiiULJOEeq_W6pXnlyepA" id="(1.0,0.16)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WuiiUbJOEeq_W6pXnlyepA" id="(0.8,0.26666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1HvOArJREeq_W6pXnlyepA" type="4001" element="_1Hum8LJREeq_W6pXnlyepA" source="_7mWaE5E9EeqRyKCsP6SKxA" target="_1HsxwLJREeq_W6pXnlyepA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1HvOBbJREeq_W6pXnlyepA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1HvOBrJREeq_W6pXnlyepA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1HvOA7JREeq_W6pXnlyepA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1HvOBLJREeq_W6pXnlyepA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5qAfU7JREeq_W6pXnlyepA" type="4001" element="_5qAfULJREeq_W6pXnlyepA" source="_8ITGsrJREeq_W6pXnlyepA" target="_5p5KkLJREeq_W6pXnlyepA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5qBGYLJREeq_W6pXnlyepA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5qBGYbJREeq_W6pXnlyepA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5qAfVLJREeq_W6pXnlyepA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5qAfVbJREeq_W6pXnlyepA" points="[0, 3, -113, 0]$[98, 3, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_9oKW8LJREeq_W6pXnlyepA" id="(0.6046511627906976,0.813953488372093)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7Q3IY7JREeq_W6pXnlyepA" type="4001" element="_7Q3IYLJREeq_W6pXnlyepA" source="_1HsxwLJREeq_W6pXnlyepA" target="_8ITGsrJREeq_W6pXnlyepA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7Q3IZrJREeq_W6pXnlyepA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7Q3IZ7JREeq_W6pXnlyepA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7Q3IZLJREeq_W6pXnlyepA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7Q3IZbJREeq_W6pXnlyepA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_TRDVgrJTEeq_W6pXnlyepA" type="4001" element="_TRCucLJTEeq_W6pXnlyepA" source="_jpW-gLJEEeq_W6pXnlyepA" target="_6vzX3bJTEeq_W6pXnlyepA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TRDVhbJTEeq_W6pXnlyepA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_TRDVhrJTEeq_W6pXnlyepA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TRDVg7JTEeq_W6pXnlyepA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TRDVhLJTEeq_W6pXnlyepA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xk5rcL03EeqGG6w3Dt49BQ" type="4003" element="_Xk4dUL03EeqGG6w3Dt49BQ" source="_UzFrIL03EeqGG6w3Dt49BQ" target="_1HsxwLJREeq_W6pXnlyepA">
      <styles xmi:type="notation:FontStyle" xmi:id="_Xk5rcb03EeqGG6w3Dt49BQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xk5rcr03EeqGG6w3Dt49BQ" points="[0, 0, -88, -15]$[90, -15, 2, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Xk7goL03EeqGG6w3Dt49BQ" id="(1.0,0.16)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DkvL8L07EeqGG6w3Dt49BQ" type="4003" element="_Dkuk4L07EeqGG6w3Dt49BQ" source="_DkqTcL07EeqGG6w3Dt49BQ" target="_xfIbiLJEEeq_W6pXnlyepA">
      <styles xmi:type="notation:FontStyle" xmi:id="_DkvL8b07EeqGG6w3Dt49BQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DkvL8r07EeqGG6w3Dt49BQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UsYz8L08EeqGG6w3Dt49BQ" type="4001" element="_UsYM4L08EeqGG6w3Dt49BQ" source="_mFZm2b0_EeqGG6w3Dt49BQ" target="_NuSY6LJFEeq_W6pXnlyepA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UsYz8708EeqGG6w3Dt49BQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UsYz9L08EeqGG6w3Dt49BQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UsYz8b08EeqGG6w3Dt49BQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UsYz8r08EeqGG6w3Dt49BQ" points="[0, 0, -226, -10]$[212, 9, -14, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UsaCEL08EeqGG6w3Dt49BQ" id="(1.0,0.42857142857142855)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UsaCEb08EeqGG6w3Dt49BQ" id="(0.09285714285714286,0.24285714285714285)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_c2GGAL08EeqGG6w3Dt49BQ" type="4001" element="_c17t8L08EeqGG6w3Dt49BQ" source="_8ITGsrJREeq_W6pXnlyepA" target="_xfIbiLJEEeq_W6pXnlyepA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_c2GGA708EeqGG6w3Dt49BQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_c2GGBL08EeqGG6w3Dt49BQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_c2GGAb08EeqGG6w3Dt49BQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_c2GGAr08EeqGG6w3Dt49BQ" points="[-32, 2, 53, -63]$[-77, 54, 8, -11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_c2HUIL08EeqGG6w3Dt49BQ" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_c2HUIb08EeqGG6w3Dt49BQ" id="(0.6357142857142857,0.15714285714285714)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_d8wMEL08EeqGG6w3Dt49BQ" type="4001" element="_d8vlAL08EeqGG6w3Dt49BQ" source="_SmndcL1AEeqGG6w3Dt49BQ" target="_-i0wwLJDEeq_W6pXnlyepA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d8wME708EeqGG6w3Dt49BQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d8wMFL08EeqGG6w3Dt49BQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d8wMEb08EeqGG6w3Dt49BQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_d8wMEr08EeqGG6w3Dt49BQ" points="[-23, 41, 32, -59]$[-58, 92, -3, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_d8xaML08EeqGG6w3Dt49BQ" id="(0.51,0.84)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_d8xaMb08EeqGG6w3Dt49BQ" id="(0.4523809523809524,0.12698412698412698)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iqpekL08EeqGG6w3Dt49BQ" type="4001" element="_iqo3gL08EeqGG6w3Dt49BQ" source="_-i0wwLJDEeq_W6pXnlyepA" target="_DREBgLJEEeq_W6pXnlyepA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iqpek708EeqGG6w3Dt49BQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iqpelL08EeqGG6w3Dt49BQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iqpekb08EeqGG6w3Dt49BQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iqpekr08EeqGG6w3Dt49BQ" points="[-27, 31, 36, -55]$[-70, 51, -7, -35]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iqqssL08EeqGG6w3Dt49BQ" id="(1.0,0.5079365079365079)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__Yp7Ir08EeqGG6w3Dt49BQ" type="4001" element="__YpUEL08EeqGG6w3Dt49BQ" source="_oaUWoLJFEeq_W6pXnlyepA" target="_AaWos709EeqGG6w3Dt49BQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__Yp7Jb08EeqGG6w3Dt49BQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__Yp7Jr08EeqGG6w3Dt49BQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__Yp7I708EeqGG6w3Dt49BQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__Yp7JL08EeqGG6w3Dt49BQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BcNuU709EeqGG6w3Dt49BQ" type="4001" element="_BcNuUL09EeqGG6w3Dt49BQ" source="_AaWos709EeqGG6w3Dt49BQ" target="_jpW-gLJEEeq_W6pXnlyepA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BcOVYr09EeqGG6w3Dt49BQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BcOVY709EeqGG6w3Dt49BQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BcOVYL09EeqGG6w3Dt49BQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BcOVYb09EeqGG6w3Dt49BQ" points="[-4, -9, -55, 0]$[42, -10, -9, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BcO8cL09EeqGG6w3Dt49BQ" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BcO8cb09EeqGG6w3Dt49BQ" id="(0.075,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CAfgEL09EeqGG6w3Dt49BQ" type="4001" element="_CAankL09EeqGG6w3Dt49BQ" source="_AaWos709EeqGG6w3Dt49BQ" target="_DREBgLJEEeq_W6pXnlyepA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CAfgE709EeqGG6w3Dt49BQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CAfgFL09EeqGG6w3Dt49BQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CAfgEb09EeqGG6w3Dt49BQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CAfgEr09EeqGG6w3Dt49BQ" points="[0, -11, 210, -33]$[19, -11, 229, -33]$[19, 45, 229, 23]$[-235, 45, -25, 23]$[-235, 30, -25, 8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CAguML09EeqGG6w3Dt49BQ" id="(1.0,0.7441860465116279)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CAguMb09EeqGG6w3Dt49BQ" id="(0.6785714285714286,0.8857142857142857)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Smp5sr1AEeqGG6w3Dt49BQ" type="4001" element="_SmpSoL1AEeqGG6w3Dt49BQ" source="_xfIbiLJEEeq_W6pXnlyepA" target="_SmndcL1AEeqGG6w3Dt49BQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Smp5tb1AEeqGG6w3Dt49BQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Smp5tr1AEeqGG6w3Dt49BQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Smp5s71AEeqGG6w3Dt49BQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Smp5tL1AEeqGG6w3Dt49BQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
